In [28]:
from qdrant_client import QdrantClient
from qdrant_client.models import Distance, VectorParams, PointStruct

import pandas as pd
import openai

### Read the sampled dataset with Amazon inventory data

In [29]:
df_items = pd.read_json("../../data/meta_Electronics_2022_2023_with_category_ratings_100_sample_1000.jsonl", lines = True)

df_items.head(2)

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together,subtitle,author
0,Industrial & Scientific,"RAVODOI USB C Cable, [2Pack/3.3ft+6.6ft] USB T...",4.4,119,[【Fast Charging Cord】These USB C cables provid...,[],NaN,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'Type-C Charger Cable ', 'url': 'ht...",RAVODOI,"[Electronics, Computers & Accessories, Compute...","{'Brand': 'RAVODOI', 'Connector Type': 'USB Ty...",B09R4Y2HKY,NaN,NaN,NaN
1,All Electronics,"SNESH-2 Pack USB-C Female to USB Male Adapter,...",4.5,352,[🔹(Light & compact) Easy to carry and light we...,[],4.99,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'USB Male & Female Adapter', 'url':...",SNESH,"[Electronics, Computers & Accessories, Compute...",{'Package Dimensions': '3.54 x 2.4 x 0.35 inch...,B09JV5FM2S,NaN,NaN,NaN

In [30]:
list(df_items["features"].items())[0]

(0,
 ['【Fast Charging Cord】These USB C cables provide up to a 3A charging current to greatly shorten the charging time, meets QC2.0 /3.0 fast charging protocol,Incredibly charge your phone from 0 to 80% in 50 minute. 480Mbps (40-60M/s) ultra fast data transmission, which leads to a faster data sync.(Note:Cables support fast charging,but require a USB-A QC3.0/QC2.0/AFC charger)',
  '【Universal Compatibility】The USB C Charger Cable is compatible with Samsung Galaxy S20 / S10 / S9 / S8+ / S8 / A02s / A03s,A12 A20 A21 A22 A23 A31 A32 A33 A41 A42 A50 A52 A52s 5G A71 A72 A73,M11 M21 M31 M51,M12 M22 M32 M52,iPad Pro 2018 / 2020,Sony Xperia XZ/X Compact/L1 / XZs / XA1 / X Premium, HTC 10 LG G5 G6,OnePlus 5T / 6T, Lumia 950 / 950XL,Huawei P9 P9 Plus P10 P10 Plus Honor Mate 9 Mate 9 pro Mate 10 pro Mate 10 lite and more',
  '【Premium Workmanship】Unique increased friction design allows you to easily unplug the cable from your charger,combine 250d bulletproof fiber core to build a cable so durable that will save your time and money.',
  '【Unbreakable Nylon Braided Cord】Premium nylon braided build a cable so durable that will outlast your phone.',
  "【What You Get】(2pack 3.3ft+6.6ft) USB A to USB C Cable with 18-Month free Warranty. If you have any questions, please don't to hesitate to contact us, we will give you a satisfied solution within 24 hours."])

In [31]:
list(df_items["images"].items())[0]

(0,
 [{'thumb': 'https://m.media-amazon.com/images/I/51G07yWoOBL._SX38_SY50_CR,0,0,38,50_.jpg',
   'large': 'https://m.media-amazon.com/images/I/51G07yWoOBL.jpg',
   'variant': 'MAIN',
   'hi_res': 'https://m.media-amazon.com/images/I/611AVJMH+JL._SL1200_.jpg'},
  {'thumb': 'https://m.media-amazon.com/images/I/41c+40oKkKL._SX38_SY50_CR,0,0,38,50_.jpg',
   'large': 'https://m.media-amazon.com/images/I/41c+40oKkKL.jpg',
   'variant': 'PT01',
   'hi_res': 'https://m.media-amazon.com/images/I/61ihhPW7VCL._SL1200_.jpg'},
  {'thumb': 'https://m.media-amazon.com/images/I/51y1YnwiUZL._SX38_SY50_CR,0,0,38,50_.jpg',
   'large': 'https://m.media-amazon.com/images/I/51y1YnwiUZL.jpg',
   'variant': 'PT02',
   'hi_res': 'https://m.media-amazon.com/images/I/61UkcVETKcL._SL1200_.jpg'},
  {'thumb': 'https://m.media-amazon.com/images/I/41Nvr++q39L._SX38_SY50_CR,0,0,38,50_.jpg',
   'large': 'https://m.media-amazon.com/images/I/41Nvr++q39L.jpg',
   'variant': 'PT03',
   'hi_res': 'https://m.media-amazon.com/images/I/611IpDcRk3L._SL1200_.jpg'},
  {'thumb': 'https://m.media-amazon.com/images/I/41QrI+i4-lL._SX38_SY50_CR,0,0,38,50_.jpg',
   'large': 'https://m.media-amazon.com/images/I/41QrI+i4-lL.jpg',
   'variant': 'PT04',
   'hi_res': 'https://m.media-amazon.com/images/I/61FQzaPa6jL._SL1200_.jpg'},
  {'thumb': 'https://m.media-amazon.com/images/I/51lezEs5DvL._SX38_SY50_CR,0,0,38,50_.jpg',
   'large': 'https://m.media-amazon.com/images/I/51lezEs5DvL.jpg',
   'variant': 'PT05',
   'hi_res': 'https://m.media-amazon.com/images/I/71qz3TFInJL._SL1200_.jpg'},
  {'thumb': 'https://m.media-amazon.com/images/I/514a4NZS1ZL._SX38_SY50_CR,0,0,38,50_.jpg',
   'large': 'https://m.media-amazon.com/images/I/514a4NZS1ZL.jpg',
   'variant': 'PT06',
   'hi_res': 'https://m.media-amazon.com/images/I/71e6ARGEtZL._SL1200_.jpg'}])

### Preprocess title and features

In [5]:
def preprocess_description(row):
    return f"{row['title']} {' '.join(row['features'])}"

In [6]:
def extract_first_large_image(row):
    return row["images"][0].get("large", "")

In [7]:
df_items["description"] = df_items.apply(preprocess_description, axis=1)
df_items["image"] = df_items.apply(extract_first_large_image, axis=1)

In [8]:
df_items.head(2)

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together,subtitle,author,image
0,Industrial & Scientific,"RAVODOI USB C Cable, [2Pack/3.3ft+6.6ft] USB T...",4.4,119,[【Fast Charging Cord】These USB C cables provid...,"RAVODOI USB C Cable, [2Pack/3.3ft+6.6ft] USB T...",NaN,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'Type-C Charger Cable ', 'url': 'ht...",RAVODOI,"[Electronics, Computers & Accessories, Compute...","{'Brand': 'RAVODOI', 'Connector Type': 'USB Ty...",B09R4Y2HKY,NaN,NaN,NaN,https://m.media-amazon.com/images/I/51G07yWoOB...
1,All Electronics,"SNESH-2 Pack USB-C Female to USB Male Adapter,...",4.5,352,[🔹(Light & compact) Easy to carry and light we...,"SNESH-2 Pack USB-C Female to USB Male Adapter,...",4.99,[{'thumb': 'https://m.media-amazon.com/images/...,"[{'title': 'USB Male & Female Adapter', 'url':...",SNESH,"[Electronics, Computers & Accessories, Compute...",{'Package Dimensions': '3.54 x 2.4 x 0.35 inch...,B09JV5FM2S,NaN,NaN,NaN,https://m.media-amazon.com/images/I/41bOA5-ogW...

In [9]:
list(df_items["description"].items())[0]

(0,
 "RAVODOI USB C Cable, [2Pack/3.3ft+6.6ft] USB Type C Fast Charging Cord - Nylon Braided USB C Charger Cable for Galaxy A20/A50/S10/S9/S8+/S8, iPad Pro 2018, Sony XZ, HTC 10, OnePlus 5T, Huawei P9 etc. 【Fast Charging Cord】These USB C cables provide up to a 3A charging current to greatly shorten the charging time, meets QC2.0 /3.0 fast charging protocol,Incredibly charge your phone from 0 to 80% in 50 minute. 480Mbps (40-60M/s) ultra fast data transmission, which leads to a faster data sync.(Note:Cables support fast charging,but require a USB-A QC3.0/QC2.0/AFC charger) 【Universal Compatibility】The USB C Charger Cable is compatible with Samsung Galaxy S20 / S10 / S9 / S8+ / S8 / A02s / A03s,A12 A20 A21 A22 A23 A31 A32 A33 A41 A42 A50 A52 A52s 5G A71 A72 A73,M11 M21 M31 M51,M12 M22 M32 M52,iPad Pro 2018 / 2020,Sony Xperia XZ/X Compact/L1 / XZs / XA1 / X Premium, HTC 10 LG G5 G6,OnePlus 5T / 6T, Lumia 950 / 950XL,Huawei P9 P9 Plus P10 P10 Plus Honor Mate 9 Mate 9 pro Mate 10 pro Mate 10 lite and more 【Premium Workmanship】Unique increased friction design allows you to easily unplug the cable from your charger,combine 250d bulletproof fiber core to build a cable so durable that will save your time and money. 【Unbreakable Nylon Braided Cord】Premium nylon braided build a cable so durable that will outlast your phone. 【What You Get】(2pack 3.3ft+6.6ft) USB A to USB C Cable with 18-Month free Warranty. If you have any questions, please don't to hesitate to contact us, we will give you a satisfied solution within 24 hours.")

In [10]:
list(df_items["image"].items())[0]

(0, 'https://m.media-amazon.com/images/I/51G07yWoOBL.jpg')

### Sample 50 items from the dataset

In [11]:
df_sample = df_items.sample(50, random_state=42)
len(df_sample)

50

In [12]:
data_to_embed = df_sample[["description", "image", "rating_number", "price", "average_rating", "parent_asin"]].to_dict(orient="records")

In [13]:
data_to_embed

[{'description': 'KEEPRO Pencil 2nd Generation for iPad, Magnetic Wireless Charge Tilt Sensitivity Palm Rejection Active Pen for Apple iPad Pro 11" 4/3/2/1, iPad Pro 12.9" 6/5/4/3, iPad Air 4/5, iPad Mini 6 [Compatibility]- ONLY compatible with iPad mini (6th generation), iPad Air (4th and 5th generation), iPad Pro 12.9-inch (3rd, 4th, 5th and 6th generation), iPad Pro 11-inch (1st, 2nd, 3rd and 4th generation), check and confirm your device before place the order (Note: If the pen doesn\'t charge, fully charge your iPad first then try charging the pen again) [Charging and Pairs Magnetically]- Charges wirelessly, attaches and pairs magnetically to the compatible iPad, this pen is a preferable alternative to the Apple Pencil 2nd Generation [Tilt Sensitivity & Pixel Precision]- Pixel-perfect precision and industry-leading low latency with tilt sensitivity making drawing, sketching, coloring, taking notes, and marking up PDFs, as easy and natural as a real pencil [Native Palm Rejection]- Rest your palm on the screen comfortably, allowing you to write and draw on your iPad as if it\'s an actual notebook [Hotkey for Easy Access]- Support Bluetooth connection to display battery percentage in the status bar, one-click return to the homepage, double-click to enter multi-task (long press 3s to turn On/Off) [Extra Replaceable Tips]- Come with 3 extra replaceable tips, keep extra tips for your pencil at the ready, the tip is compatible with Apple Pencil (1st generation) and Apple Pencil (2nd generation)',
  'image': 'https://m.media-amazon.com/images/I/21XciKpEmpL._AC_.jpg',
  'rating_number': 2131,
  'price': 22.97,
  'average_rating': 4.3,
  'parent_asin': 'B0BF18F6R7'},
 {'description': 'HOSONGIN 1/4 TRS Stereo Jack to Dual 1/4 TS Mono Y-Splitter Insert Cable, Nylon Braided Jacket Gold-Plated Plug Double Shielding Cable, 1 Feet EASILY CONNECT DEVICES: HOSONGIN 1/4 inch TRS Stereo Female to Dual 1/4 inch Y-Splitter Cable uses a 1/4" TRS stereo cable to connects a Mixer, Amplifier, Headphones, Speaker, or other devices with 6.35mm 1/4" TRS output to Hi-Fi stereo, speakers, or other pro audio gear with Dual 2x 6.35mm 1/4" TS Mono jack Stereo inputs. STANDARD CONNECTORS: HOSONGIN 1/4 inch TRS Stereo Female to Dual 1/4 inch TS Mono Y-Splitter Cable uses standard audio connectors, a 6.35mm(1/4 inch) TRS Female connector on one end, and two 1/4" TS Mono connectors on the other end. It splits a stereo signal into L-R audio over two 1/4 inch TS cables. CLEAN & CLEAR SOUND: HOSONGIN 1/4 inch TRS Stereo Female to Dual 1/4 inch TS Mono plug Y-Splitter Cable uses double shielded layers, tinned copper wire core, and corrosion-resistant gold-plated connector prevents EMI & RFI Signal Interference, ensuring the Highest Quality audio transfer without static or popping. STRONG DURABLE DESIGN: The HOSONGIN Audio Cable\'s Plugs with Aluminum Alloy Shell and Molding technology prolong service life; the beveled step-down design ensures a secure, fully plugged-in connection; the premium braided jacket exterior offers added strength and flexibility, tangle-free. AMAZING SHOPPING EXPERIENCE: You will get 1 x HOSONGIN 1/4 inch TRS Stereo Female to Dual 1/4 inch Y-Splitter Cable, Not only that, you will become our forever VIP customer, and we will provide you with a full range of customer service and product services. Don\'t hesitate to contact us with any questions, and we will reply to you within 12 hours.',
  'image': 'https://m.media-amazon.com/images/I/41J3p7fyJHL.jpg',
  'rating_number': 114,
  'price': 14.99,
  'average_rating': 4.6,
  'parent_asin': 'B0B96LV4C5'},
 {'description': 'Tenda A33 AX3000 WiFi 6 Extender, WiFi Booster WiFi Range Extender, 2.4/5GHz Dual Band WiFi Extender with Ethernet Port, AP Mode, WPS Easy Setup, WiFi Extenders Signal Booster for Home Improved WiFi Coverage - With 2 * 5dbi dual-band antennas, the Tenda A33 wifi extender can effectively boost your wifi signal for up to 2100 sq. ft coverage , providing you a stable wifi connection at your home with no dead zone. Fast Speed - Tenda A33 WiFi 6 Range Extender provides maximum speeds of 574Mbps on the 2.4GHz band and 2402Mbps on the 5GHz band, delivering you an unrivaled network experience at every corner of your house. More Devices, Less Latency - Compared with the previous WiFi 5 generation, WiFi 6 technology enables 1.5X better performance in speed and latency. You can connect to 20+ devices without issues like speed drop and network congestion. All-around WiFi Extender - Tenda A33 comes with a Gigabit Ethernet Port for demanding task like gaming and streaming. You can also use the access point mode to get the best possible speed from your network without worrying about interfering signal. Intelligent Roaming – Tenda A33 WiFi Repeater uses your existing network SSID name by default to ensure a seamless network experience around your home. Compatibility Note: The Tenda A33 is compatible with 99% wifi routers in the market. However, if you want to extend a mesh network, adding a mesh node would be recommended as most mesh systems remove the "AP Client" feature that is necessary for a wifi extender to work.',
  'image': 'https://m.media-amazon.com/images/I/31dq3Sl6OnL._AC_.jpg',
  'rating_number': 560,
  'price': 84.99,
  'average_rating': 4.4,
  'parent_asin': 'B0BZ5R7CVP'},
 {'description': 'Bluetooth Transmitter Receiver, 5.0 Bluetooth Adapter with 3.5mm RCA TF Card Playback, 2-in-1 Audio Adapter, Bluetooth Car Adapter for PC/TV/Speaker/Headphones/Home Low Latency 【2-In-1 Bluetooth Transceiver】 In the transmitter mode, the Bluetooth adapter can be paired with a Bluetooth headset or speaker. In the receiver mode, it can be connected to the traditional wired speaker stereo receiver, the auxiliary input port of the car adapter, make them wireless, and connect the mobile phone or tablet to play your favorite music. 【Featured TF Card Slot】Fossduck bluetooth adapter for stereo receiver is featured for the TF card slot. You can choose either to play from your smart device or TF card! No matter you are using an old speaker, vintage stereo, or car stereo system, you can easily turn the music into wireless via the 3.5 mm or RCA cables of the bluetooth audio receiver. 【LED Display Screen & Button Control】 The display will show the Bluetooth status, and press the previous/next track key at the same time to switch the transmit and receive mode 【Great Sound Quality】Fossduck bluetooth transmitter receiver can transmit stereo audio wirelessly from your non-bluetooth audio sources such as tv, mp3, cd player, pc or ebook reader to your bluetooth-enabled headphones, speaker or receiver. This way, you can enjoy high quality music wirelessly or listen to late night shows without disturbing your loved ones while they sleep. 【Wide Cover Range】Fossduck stereo receiver with bluetooth can cover up to 50-70ft range with a reliable connection. No more wires limit and definitely offer you much more convenience with a fluent, enjoyable music experience',
  'image': 'https://m.media-amazon.com/images/I/41ih5c0-XkL._AC_.jpg',
  'rating_number': 220,
  'price': nan,
  'average_rating': 3.9,
  'parent_asin': 'B09PFSVK44'},
 {'description': 'iPhone Charger Cord Lightning Cables, Original 2022 Upgraded [3Pack 3ft] Apple MFi Certified USB A Charging Cable for iPhone 13 12 11 Mini Pro XR Xs Max X SE 8 7 6 Plus iPad iPod AirPods - Black Original Apple Cable - iPhone charging cable with a reinforced joint design that has passed 30,000+ times bending tests for extra protection and durability. Insulation and precisely layer-welded connectors, which make the cable more durable and sturdier than normal iPhone charger cables but also flexible and tangle-free. Instant Responses - No error message pops up. Real high-speed iPhone charging cable with stable and efficient current output, you can plug it into laptop computers and in-car charging adapter. Super Fast Charge - The iPhone Lightning cable build-in four-core high-quality copper wires and multiple safety protections overcharge/stable current/automatic switching/battery protection to promote maximum signal quality and strength. You can enjoy faster charging [3.0A] and safer high-speed data transferring [480Mbps]. Apple MFi Certified - Lightning cable ensure 100% compatibility with iPhone 13, 13 Pro, 13 Pro Max, 13 Mini, 12, 12 Mini, 12 Pro, 12 Pro Max, SE 2020, iPhone 11, 11 Pro, 11 Pro Max, XR , Xs , Xs Max, X, 8, 8 plus, 7, 7 plus, 6s, 6s plus, 6, 6 plus, SE, 5s, 5, 5c, iPad Pro, iPad Air, iPad Air 2, iPad mini, mini 2, mini 3, mini 4, Mini 6, iPad 4, iPad 9, iPod Touch (5 Gen), iPod Nano 7. What You Get? - 3-foot long MFI apple certified iPhone charger cable 3 pack, if you have any questions, please feel free to contact us. Notice: Please make sure to make a purchase in the store! Otherwise, we will not be able to guarantee its authenticity, and we do not provide any after-sale services for other stores!',
  'image': 'https://m.media-amazon.com/images/I/41lk7yDhf3L.jpg',
  'rating_number': 4709,
  'price': 12.59,
  'average_rating': 4.5,
  'parent_asin': 'B0BYYLJRHT'},
 {'description': 'Punoge Small USB Desk Fan - 5.3 Inch Portable Table Fan with 3 Levels Air Flow, 8 Color LED Lights, 360° Rotation, Quiet Mini Personal Fan for Home Office Desktop Innovative Portable Desk Fan - Why bring a boring fan to your home if you can find such a distinctive one with 3 adjustable wind speed, 8 different color light and 360° Rotatable stand? With its small size: 5.5* 3.5* 5.8in (14.1*9*14.7cm), you could put it anywhere on the tabletop of your home or office. Say goodbye to hot flashes, sweating, and flushing from now on 3 Levels Wind Speed Adjustable - This table fan provides 3 levels air flow for you to choose from. Just press one button you could select a comfortable wind speed. The maximum speed of this desk fan is up to 3300 RPM, so you get instant cool feeling as soon as you turn it on. And it’s quiet enough for you to use at home or office, the wind noise is below 45dB for the lowest level 8 Colors Atmosphere Light - This personal fan is equipped with 8 different colors LED light function. One press of the light button you could switch to the color you like, you will no longer feel boring when you’re working or gaming in hot weather. This desktop fan would also be a great gift choice USB Powered - The table fan is powered by a 4.9ft USB cable, you can plug it into all USB ports like laptops, computer, power banks or other USB-enabled power supplies. NOTE: This USB fan do not contain any battery, and it’s not rechargeable Premium Tabletop Fan - 360° rotatable fan to provide wind in any desired direction. Smooth and sleek design made of high grade ABS material, makes it a modern decor for your home or office. What you get: A Desk Fan with USB cable, a User Manual',
  'image': 'https://m.media-amazon.com/images/I/41ttrJKbfFL._AC_.jpg',
  'rating_number': 117,
  'price': nan,
  'average_rating': 4.7,
  'parent_asin': 'B0B1MPKCS8'},
 {'description': '8 Pairs Powerbeats Pro Ear Tips Buds, 4 Size Replacement Soft Flexible Fit in Case Noise Reduce Silicone Rubber Earbuds Eartips Wing Skin Accessories Compatible with Beats Flex/BeatsX - White 【 Compatibility 】 These ear tips compatible with Powerbeats Pro, compatible with Powerbeats High Performance, compatible with Beats Flex, compatible with Beats X, compatible with Beats Fit Pro, compatible with Beats Studio Buds. 【 Material 】 Made of soft flexible premium silicone, provide more noise isolation, in-ear stability and a lasting comfort. And They are Water-washable, durable, flexible, removable and replaceable. 【 Nice Sound Quality 】 These ear tips can offer a good seal to reduce some of the outside noise and allow you to focus on your audio, provide a better sound listening experience. 【 More Size Options, Better Fit 】 Small Medium Large and Double Flange 4 different sizes, complies comfortably with your individual ear shape. Fit in the charging case, no need to remove the foam when you put earphone into the charging case. 【 Package include 】 8 pairs replacement ear tips, tips only, earphone not include.',
  'image': 'https://m.media-amazon.com/images/I/31Q1I3K1KuL._AC_.jpg',
  'rating_number': 269,
  'price': 7.99,
  'average_rating': 4.5,
  'parent_asin': 'B0B14HTZ59'},
 {'description': 'Crodi Engraved Christmas & Halloween Band Compatible with Fitbit Versa 4/Versa 3/Sense 2/Sense Band Women Men Fadeless Pattern Silicone Sports Solo Loop Soft Strap ONLY for Versa 4/Sense 2 Buckle closure 🎄Fadeless Christmas Watch Band: The engraved Christmas Tree pattern from the unique design inspiration that makes it stand out from traditional silicone bands. The engraving process allows the pattern on the band to last for a long time without fading. This strap adds character to your Versa 4/Versa 3/Sense 2/Sense smartwatch band. 🎄Skin-friendly material with classic Clasp design: Made of skin-friendly silicone material, it is waterproof and dustproof while reducing the occurrence of skin irritation. The washable feature allows it to excel in sports, beach vacations, and hot weather.Best of all, having a real buckle instead of those studs that push through the hole, keeps it secure on wrist. 🎄A universal band for many occasions: A stylish and unique band for anyone. Whether it\'s for sports, travel, party, work, or just hanging out it can be the perfect match for your watch. Add fashionable and trendy style to you. It is only compatible with Fitbit Versa 4/Versa 3/Sense 2/Sense smartwatch. Please confirm your watch model before purchase. 🎄Attractive, Sweet and Practical Gift:It has enough holes for length adjustment and can fit wrists from 5.25"-7.3". The unique printed wristband with posh embossed Christmas pattern design gives you a lightweight, soft, youthful and energetic feeling. it can be a stylish gift for family friends or lovers. 🎄Enjoy Your Watch Band: One-year warranty,and 24/7 online service.We will refund or free replacement if you have any concerns or dissatisfaction.（Watches NOT Include） We will do our best to keep providing better products and better service.',
  'image': 'https://m.media-amazon.com/images/I/41oB2HWqMUL._AC_.jpg',
  'rating_number': 112,
  'price': 6.99,
  'average_rating': 4.4,
  'parent_asin': 'B0BB1YKXL1'},
 {'description': "MUXA 6 Pack [Apple MFi Certified] 3/3/6/6/10/10 FT iPhone Charger Colorful Nylon Lightning Cable Compatible iPhone 13 mini/13/12/11 Pro Max/XS MAX/XR/XS/X/8/7/Plus/6S/6/SE/5S/iPad ♦Perfectly Compatibility♦ : Work with iPhone 13 12 11, 13 12 11 Pro, 13 12 11 Pro Max,13 12 Mini, XS Max, XS, XR, X, 8 Plus, 8, 7 Plus, 7, 6S Plus, 6S, 6 Plus, 6, 5S, 5C, 5, iPad iPod . ♦Multiple Enjoyment♦ : Precise interface design, Fits enoughly to your charging port, no need to remove the phone case, solve tedious troubles, and charge when you want to charge all the time.Cables long enough to be convenient to charge your device in bedroom, sofa, office, travel，even when you are on the backseat of the car. ♦MFi Certified iPhone Charger♦ : MFI Certified Lightning Cable, Built with terminal and smart chip, ensured safe charging for your devices and Enjoy fast charge and data transfer. ♦Strengthened Durability♦ : It will be more durable than iPhone cable you have ever seen. It has a service life of 12 times longer than other cables, and has been proven to withstand 12,000 cycles + bending in rigorous laboratory tests. ♦Sweet Service♦ : If you have any questions about the product, please don't hesitate to contact us immediately and we will answer you within 24 hours.",
  'image': 'https://m.media-amazon.com/images/I/61rpS-eHRTL.jpg',
  'rating_number': 3922,
  'price': 11.99,
  'average_rating': 4.5,
  'parent_asin': 'B09TNXY54Y'},
 {'description': '1TB USB Flash Drives, NEIGHBOR Portable Thumb Drive 1TB USB Memory Stick, Metal 1000GB USB Drive High-Speed Waterproof Jump Drive for Data Storage and Transfer 【Reliable & Durable】The usb memory stick adopts Grade-A chips and high quality flash memory particles, safeguards your data and transfers your data seamlessly. Quicker heat dissipation permits longer service life. Suitable for storing digital data for school, business or daily usage. With Small size, these flash drives are readily available wherever you go. 【Excellent Compatibility】Ultra High Speed 1TB Flash Memory Stick is plug and play without any software installation; Simply insert the USB 3.0 Pen Drive 1000GB into the device to transfer and store data between the devices. The USB Flashdrives Supports Windows 7/8/10 / Vista / XP / Unix / 2000 / ME / NT Linux and Mac OS, and is compatible with USB 1.1, USB 2.0 and USB 3.0 ports. 【High Quality】USB Flash Drive 1TB features durable and rugged Metal housing body. The inside uses the most advanced imported smart chip, assembled through many complicated and strict processes. Therefore, it has excellent water resistance, magnetic resistance, high-temperature resistance, and X-ray resistance, thus ensuring that its service life far exceeds other similar products, which makes you store your data with more confidence. 【Powerful Storage Functions】USB Thumb Drive 1TB can transfer up to 204800 photos[10 megapixels]; 102400 MP3 audio files; 2560 minutes HD videos[1080P resolution] or 5120 minutes HD videos [720P resolution]. 1TB Flash Memory Stick is commonly used for storage, data backup and computer file transfer, it will meet your needs of daily use on work, school, home, and traveling for photos, music, videos, files storage and transfer. 【24 Hour Warm Customer Service】USB flash drive 1000GB widely use on personal use and meet your business needs in daily life.We always try our best to provide 100% customer satisfaction.Please click contact us if you have any quality issues.We are always here to address your problem in 24 hours.',
  'image': 'https://m.media-amazon.com/images/I/31jZHJYSgfL._AC_.jpg',
  'rating_number': 107,
  'price': 25.99,
  'average_rating': 4.8,
  'parent_asin': 'B0CF57H28T'},

### Define the embedding function
Remember to add this library at the top  
import openai

In [14]:
response = openai.embeddings.create(
    input = "Random text",
    model = "text-embedding-3-small",
)

In [15]:
len(response.data[0].embedding)

1536

In [16]:
response

CreateEmbeddingResponse(data=[Embedding(embedding=[-0.015929508954286575, -0.003945682197809219, 0.008374194614589214, 0.003673366503790021, -0.04285980761051178, -0.06279100477695465, -0.007875914685428143, 0.011989621445536613, -0.013024807907640934, -0.006133865565061569, -0.006751887500286102, 0.011811939999461174, -0.020750079303979874, 0.03782292827963829, 0.028428999707102776, -0.018556101247668266, -0.0320444256067276, -0.006670772098004818, -0.05052327364683151, 0.033620379865169525, -0.015504620037972927, 0.024350056424736977, -0.020209310576319695, 7.604563870700076e-05, 0.019127771258354187, -0.0015411917120218277, 0.01582135632634163, -0.008675480261445045, 0.03640148043632507, -0.03637057915329933, 0.024489110335707664, -0.04298340901732445, 0.022465089336037636, -0.025431593880057335, 0.014029093086719513, 0.009123546071350574, 0.050399672240018845, 8.268454985227436e-05, 0.022511441260576248, 0.0023098562378436327, -0.003134528873488307, -0.047433167695999146, 0.031611811369657516, 0.027532868087291718, 0.030066756531596184, 0.02628137357532978, -0.019884848967194557, -0.007601667195558548, 0.035474445670843124, 0.061585865914821625, -0.04845290258526802, 0.026729438453912735, 0.002263504546135664, 0.048174794763326645, -0.00563172297552228, -0.01807713508605957, -0.0368649959564209, 0.044281255453825, -0.018169838935136795, -0.021831616759300232, 0.021167244762182236, 0.0013944115489721298, -0.018942365422844887, 0.024504560977220535, 0.029711393639445305, 0.004001690540462732, -0.025277087464928627, 0.03519633784890175, 0.01693379506468773, 0.04261259734630585, -0.0010120106162503362, -0.005430866032838821, -0.06656093895435333, 0.0002947673783637583, -0.03541264310479164, 0.0063347225077450275, 0.006145453546196222, -0.01135614886879921, 0.00521842110902071, 0.025014428421854973, 0.041283849626779556, 0.03912077471613884, -0.024906275793910027, -0.018138937652111053, -0.06257469952106476, -0.0021147930528968573, -0.1081537976861, -0.007431711070239544, -0.004534734413027763, -0.02384018711745739, -0.024720868095755577, 0.0022557792253792286, -0.04329242184758186, -0.006945019122213125, 0.0007353492546826601, 0.004067355301231146, 0.014059994369745255, 0.03467101976275444, 0.024859923869371414, -0.012646269053220749, 0.014948400668799877, -0.03671048954129219, -0.01135614886879921, 0.0010081479558721185, -0.018695157021284103, 0.006462189368903637, -0.008775908499956131, -0.03392939269542694, -0.04264349862933159, 0.018339794129133224, -0.06390344351530075, -0.028954317793250084, 0.018741508945822716, -0.005627860315144062, -0.0169492457062006, -0.027641020715236664, 0.04363233223557472, 0.002541614230722189, 0.004055767320096493, -0.033064160495996475, -0.0026632873341441154, -0.008443721570074558, 0.019807595759630203, -0.03989330306649208, -0.02997405268251896, -0.036246974021196365, -0.0070995246060192585, -0.023762935772538185, -0.009942424483597279, 0.009409381076693535, 0.04734046384692192, -0.0320444256067276, -0.007215403486043215, -0.011093489825725555, -0.06464507430791855, -0.0046776519156992435, -0.0038819490000605583, -0.0062033929862082005, -0.05287175625562668, 0.03222983330488205, -0.013434247113764286, -0.013627379201352596, -0.0015025653410702944, -0.02067282609641552, -0.0015363633865490556, -0.02201702445745468, -0.02107454091310501, -0.012082324363291264, 0.012507214210927486, 0.0032137129455804825, -0.042025476694107056, 0.039986006915569305, -0.054849427193403244, 0.024844473227858543, 0.04097484052181244, -0.028073636814951897, 0.03148820623755455, 0.016485730186104774, -0.03633967787027359, -0.018865112215280533, -0.010189632885158062, -0.01977669447660446, 0.00577464047819376, 0.004364778287708759, -0.022403286769986153, -0.011572456918656826, 0.04372503608465195, -9.065123595064506e-05, -0.08701746165752411, 0.011232544668018818, -0.004685377236455679, -0.05308806523680687, -0.050770483911037445, 0.003032169071957469, -0.021908869966864586, 0.020379265770316124, 0.01062224805355072, -0.011472027748823166, -0.0071458760648965836, 0.06325452029705048, 0.038131941109895706, 0.063347227871418, 0.023438474163413048, -0.0014938743552193046, -0.004542459733784199, -0.05203742906451225, 0.03572165593504906, -0.005566058214753866, 0.0030263750813901424, 0.005508118774741888, -0.026343176141381264, 0.01387458760291338, 0.030468471348285675, -0.0040248665027320385, -0.014600763097405434, -0.027100251987576485, 0.05472582206130028, 0.0015276724006980658, -0.013480599038302898, 0.0089381393045187, 0.03238433972001076, 0.05382969230413437, -0.011186192743480206, -0.011719237081706524, -0.046660639345645905, -0.04789668321609497, -0.025802407413721085, 0.01342652179300785, -0.005905969999730587, -0.00452314643189311, 0.11495204269886017, -0.04842200130224228, -0.026899395510554314, -0.048885516822338104, -0.057290613651275635, -0.040913037955760956, 0.04097484052181244, 0.03596886247396469, 0.009664314799010754, -0.028181789442896843, -0.01062224805355072, 0.041809167712926865, 0.06099874526262283, 0.02257324382662773, 0.0002773855230771005, 0.011217094026505947, 0.05834124982357025, -0.001508359215222299, 0.0004302010638639331, 0.04066582769155502, 0.05661078914999962, 0.005554470233619213, 0.01792263053357601, -0.04150015860795975, 0.0592682845890522, 0.02830539457499981, 0.013001631945371628, 0.0049094101414084435, 0.00352079258300364, 0.03053027205169201, -0.01749001443386078, -0.0144462576135993, 0.0376066230237484, 0.026497680693864822, 0.03763752430677414, -0.031611811369657516, -0.019096871837973595, -0.036463283002376556, 0.04545549675822258, 0.0025049191899597645, 0.028274493291974068, -0.0169492457062006, -0.01733550988137722, -0.003993965219706297, 0.02665218710899353, -0.035659853368997574, -0.0007937716436572373, 0.027656471356749535, 0.031580910086631775, -0.03334227204322815, -0.044435761868953705, -0.04418855160474777, -0.06711716204881668, 0.007211540825664997, -0.0052840858697891235, -0.02367023192346096, 0.030267613008618355, -0.015118355862796307, 0.028382647782564163, -0.05948458984494209, -0.014291752129793167, -0.017968980595469475, 0.005654898937791586, 0.031148293986916542, 0.009278050623834133, 0.044806573539972305, -0.016871992498636246, -0.0009072365937754512, -0.02629682421684265, 0.027641020715236664, -0.0210281889885664, 0.011232544668018818, -0.03244613856077194, -0.019900299608707428, -0.024272803217172623, -0.011734687723219395, 0.04403404891490936, 0.005484942812472582, 0.023979242891073227, 0.0003304967831354588, -0.010452291928231716, -0.017567267641425133, 0.04211818054318428, -0.019807595759630203, -0.004179371986538172, 0.016315773129463196, 0.027069350704550743, 0.024689966812729836, -0.006547167431563139, 0.013063434511423111, 0.051697514951229095, 0.005716701038181782, 0.013704631477594376, 0.025416143238544464, -0.02252689190208912, 0.03275515139102936, 0.0031615672633051872, -0.010854006744921207, 0.027702823281288147, -0.015056554228067398, 0.0011037482181563973, 0.033434975892305374, -0.002427666448056698, -0.009293501265347004, -0.032909657806158066, -0.032878756523132324, 0.013295192271471024, 0.04029501602053642, 0.0588974691927433, -0.0781797468662262, 0.07490423321723938, -0.05478762462735176, 0.06170946732163429, -0.022063374519348145, 0.007783210836350918, -0.013534675352275372, 0.05781593173742294, 0.03002040460705757, 0.05216103419661522, -0.011920093558728695, -0.01156473159790039, -0.03365128114819527, 0.03210622817277908, 0.004948036279529333, 0.0514812096953392, -0.03933708369731903, -0.014654840342700481, 0.0324152372777462, 0.05345887690782547, 0.00025541678769513965, -0.01221365388482809, 0.013658279553055763, 0.002421872690320015, -0.055621955543756485, -0.009548435918986797, -0.05682709813117981, -0.00759780453518033, 0.0044343057088553905, -0.021368101239204407, 0.0139827411621809, -0.0033315233886241913, 0.02176981419324875, 0.017968980595469475, -0.06588111817836761, -0.0028602818492799997, -0.014994751662015915, 0.020456518977880478, 0.024859923869371414, 0.009502083994448185, 0.015381015837192535, 0.018679706379771233, 0.02832084521651268, 0.018308892846107483, -0.023144913837313652, 0.03396029397845268, 0.017814476042985916, -0.037730224430561066, 0.0100505780428648, 0.009200798347592354, -0.023948341608047485, -0.03522723913192749, 0.02890796586871147, -0.02048742026090622, 0.001341300318017602, -0.028459900990128517, 0.009749292396008968, -0.02011660672724247, 0.032909657806158066, 0.04214908182621002, 0.037575721740722656, -0.0287071093916893, 0.02611141838133335, -0.03090108558535576, -0.019792145118117332, 0.03593796119093895, 0.02158440835773945, 0.028428999707102776, 0.010359589010477066, -0.04734046384692192, -0.008389645256102085, 0.008768183179199696, 0.021120892837643623, -0.015535521320998669, 0.03507273271679878, -3.03126380458707e-05, 0.014932950027287006, -0.0038780863396823406, 0.02346937544643879, -0.02518438547849655, -0.0042682127095758915, 0.05382969230413437, -0.00429138820618391, -0.039213478565216064, 0.016702037304639816, -0.026775790378451347, 0.019884848967194557, -0.0257406048476696, 0.029016120359301567, 0.04675334319472313, 0.007798661477863789, 0.04044952243566513, -0.014399905689060688, 0.034392908215522766, 0.009193073026835918, -0.0149097740650177, 0.009641138836741447, 0.07737632095813751, 0.006720986217260361, 0.0005499427788890898, 0.05052327364683151, -0.028938867151737213, -0.021877968683838844, -0.03779202699661255, -0.02363933064043522, -0.011247995309531689, 0.05571465939283371, 0.050430573523044586, -0.03831734508275986, -0.01619216986000538, -0.029695942997932434, -0.0008068080642260611, -0.02331486903131008, -0.016114916652441025, -0.0037061988841742277, 0.02906247042119503, -0.010753577575087547, -0.019823046401143074, 0.030978338792920113, -0.011773313395678997, -0.03896626830101013, -0.014562136493623257, 0.024164648726582527, -0.07063988596200943, 0.008729556575417519, -0.027254758402705193, 0.018896013498306274, 0.017428211867809296, 0.013882312923669815, -0.035876162350177765, -0.044991981238126755, -0.012769874185323715, -0.02553974837064743, -0.0065317172557115555, -0.04075853154063225, 0.03331137076020241, -0.033465877175331116, 0.03915167599916458, 0.013581027276813984, -0.0022557792253792286, 0.026219571009278297, 0.015612773597240448, -0.029865900054574013, -0.028583504259586334, 0.001096022897399962, 0.02890796586871147, -0.06041162461042404, -0.007226991467177868, 0.04282890632748604, 0.04285980761051178, -0.006357898470014334, -0.015473718754947186, 0.012090049684047699, 0.008289216086268425, 0.02550884708762169, 0.006191805005073547, -0.02719295583665371, 0.029572339728474617, -0.062296587973833084, -0.011147567071020603, 0.024473659694194794, 0.032137129455804825, 0.003165429923683405, 0.013117510825395584, 0.002437323099002242, -0.01696469634771347, 0.08565781265497208, -0.007605529855936766, 0.022295134142041206, 0.015141531825065613, -0.011155292391777039, -0.031565457582473755, 0.020178409293293953, 0.02983499877154827, -0.019452232867479324, 0.03142640367150307, -0.03144185617566109, -0.014631664380431175, -0.03229163587093353, -0.010954434983432293, -0.06538669764995575, -0.011920093558728695, 0.0036617787554860115, -0.01952948607504368, 0.02217152900993824, 0.02663673646748066, 0.019483134150505066, 0.012777598574757576, 0.0029838860500603914, 0.003063070122152567, 0.02815089002251625, 0.01656298153102398, 0.00039929995546117425, 0.005260909907519817, -0.016856541857123375, -0.007644155994057655, 0.008992215618491173, -0.013843686319887638, -0.006755749695003033, -0.01060679741203785, -0.046660639345645905, 0.032353438436985016, 0.030082207173109055, 0.012878027744591236, -0.014647115021944046, 0.005905969999730587, -0.05117219686508179, -0.036030665040016174, -0.023438474163413048, -0.0028177928179502487, 0.008119259960949421, 0.010537270456552505, 0.008466897532343864, 0.07508964091539383, 0.0162076186388731, -0.002844831207767129, -0.037174005061388016, -0.006075926125049591, 0.00493644829839468, 0.03803923726081848, 0.005554470233619213, 0.012429961934685707, 0.04119114577770233, 0.04261259734630585, -0.01258446741849184, -0.04561000317335129, 0.02662128582596779, 0.01406771969050169, -0.003657916095107794, 0.0018173700664192438, -0.010823105461895466, 0.020580124109983444, -0.004646750632673502, -0.0016879718750715256, -0.017783574759960175, 0.03414570167660713, -0.009363029152154922, -0.0012553565902635455, 0.02382473647594452, 0.03222983330488205, 0.013673730194568634, 0.010390490293502808, 0.0008256384171545506, -0.0005958115798421204, 0.007385359611362219, -0.015944959595799446, 0.010375039651989937, -0.024998977780342102, 0.04459026828408241, 0.03705040365457535, -0.02828994393348694, 0.020008452236652374, 0.017242806032299995, 0.0033682184293866158, -0.03144185617566109, -0.010691775940358639, -0.0025300264824181795, 0.032477039843797684, -0.005322712007910013, -0.02586420811712742, 0.019096871837973595, -0.0070995246060192585, 0.0335276797413826, 0.028382647782564163, 0.027656471356749535, -0.04922543093562126, 0.034949127584695816, 0.0075475904159247875, -0.017999881878495216, 0.0033894628286361694, 0.003874223679304123, 0.04585720971226692, 0.024319155141711235, -0.0026961197145283222, 0.0361233688890934, 0.000601605512201786, 0.00987289659678936, -0.014708916656672955, -0.03800833597779274, -0.03578345850110054, -0.0015296037308871746, 0.033620379865169525, -0.004442031029611826, -0.0051488932222127914, -0.015172433108091354, 0.021337199956178665, 0.016470279544591904, -0.009903797879815102, -0.01750546507537365, 0.014770719222724438, -0.04394134506583214, -0.0071845026686787605, 0.014229950495064259, 0.006748024839907885, -0.015736378729343414, -0.020193859934806824, 0.00679437629878521, -0.03312596306204796, -0.010583622381091118, 0.008621403016149998, 0.017984431236982346, -0.02964959107339382, 0.0020954799838364124, 0.04029501602053642, -0.008675480261445045, -0.03930618241429329, 0.0023929027374833822, -0.015265136025846004, -0.021182693541049957, 0.014562136493623257, -0.009169897064566612, 0.006315409205853939, -0.0011732756393030286, -0.0005779468920081854, -0.020193859934806824, -0.008443721570074558, -0.010954434983432293, 0.022295134142041206, 0.00913899578154087, 0.01174241304397583, -0.025570647791028023, 0.03162726014852524, -0.009617962874472141, 0.01389003824442625, -0.02830539457499981, 0.04418855160474777, -0.009100370109081268, 0.022635044530034065, 0.01585225760936737, 0.011842841282486916, -0.0387190617620945, -0.016532080247998238, -0.0025609275326132774, 0.004982800222933292, -0.01482479553669691, -0.008644578978419304, -0.02197067253291607, -0.005948459263890982, -0.02345392480492592, -0.004457481671124697, -0.028073636814951897, -0.0068561783991754055, -0.01915867254137993, -0.01527286134660244, -0.007207678165286779, -0.03695769980549812, 0.045331891626119614, -0.028738010674715042, -0.026961198076605797, -0.014469433575868607, 0.023886539041996002, 0.0010747783817350864, 0.03148820623755455, -0.001085400697775185, -0.008088359609246254, 0.02122904546558857, 0.013851411640644073, 0.004951898939907551, -0.045919012278318405, 0.010552721098065376, -0.008466897532343864, 0.014229950495064259, 0.010575897060334682, -0.02028656378388405, -0.016702037304639816, -0.02382473647594452, 0.033836688846349716, 0.02625047229230404, 0.01826254092156887, -0.03284785524010658, -0.015033378265798092, -0.04564090445637703, -0.026374077424407005, 0.04638253152370453, 0.022882254794239998, 0.020626474171876907, -0.009471182711422443, 0.006052750162780285, 0.025586098432540894, -0.02964959107339382, -0.036988601088523865, 0.012491763569414616, 0.017999881878495216, -0.020997287705540657, 0.01510290615260601, 0.015697751194238663, -0.041067544370889664, 0.02141445316374302, -0.021692562848329544, 0.021708013489842415, 0.0009019254357554018, 0.0004850022087339312, -0.008613677695393562, -0.01323338970541954, -0.0027366774156689644, -0.02311401255428791, 0.01807713508605957, 0.009115820750594139, -0.026327725499868393, -0.0084746228531003, -0.005662623792886734, 0.01107031386345625, 0.03318776562809944, 0.015010202303528786, -0.01585225760936737, -0.023206716403365135, -0.03473282232880592, 0.02591056004166603, -0.0331568643450737, -0.0030360317323356867, 0.052253738045692444, 0.006836865097284317, 0.011410226114094257, 0.044281255453825, -0.020456518977880478, 0.001124992617405951, -0.0017980568809434772, -0.01154928095638752, -0.01767542026937008, 0.0016165130073204637, -0.004851470701396465, 0.0002882491971831769, -0.004851470701396465, 0.00652399193495512, 0.02535434067249298, -0.010568171739578247, 0.014029093086719513, 0.037019502371549606, -0.0003304967831354588, -0.010676325298845768, -0.0033431111369282007, -0.049441736191511154, 0.014291752129793167, -0.02176981419324875, -0.017273707315325737, -0.009741567075252533, -0.03470192104578018, 0.041994575411081314, 0.0010216671507805586, 0.014392180368304253, 0.07329737395048141, -0.003238820005208254, 0.0424271896481514, -0.00265556201338768, 0.036463283002376556, -0.04347782954573631, -0.025632450357079506, -0.008142435923218727, 0.0053922394290566444, -0.01435355469584465, 0.013503775000572205, 0.013117510825395584, -0.007717546075582504, -0.015419641509652138, 0.010035127401351929, 0.01276214886456728, -0.017026498913764954, -0.05837215110659599, 0.03973879665136337, -0.005670349113643169, -0.023932890966534615, -0.007736859377473593, 0.016470279544591904, -0.03281695395708084, 0.021553507074713707, -0.008343293331563473, -0.01639302633702755, 0.03674139082431793, 0.015218785032629967, 0.005793953780084848, -0.004175509326159954, 0.008196513168513775, -0.0585266575217247, 0.030962888151407242, -0.02442730776965618, -0.02496807649731636, 0.015790455043315887, -0.006581931374967098, -0.08009561151266098, 0.018108036369085312, -0.002688394393771887, 0.02146080508828163, -0.005295673385262489, 0.002004707930609584, 0.04004780575633049, 0.030236711725592613, -0.005423140712082386, -0.024689966812729836, 0.039244379848241806, -0.020178409293293953, -0.020023902878165245, -0.004414992872625589, 0.013480599038302898, -0.011541555635631084, 0.012808499857783318, -0.021939771249890327, -0.0405731275677681, -0.02275864966213703, -0.028228141367435455, -0.007702095899730921, 0.03596886247396469, -0.01358875259757042, -0.02220243029296398, -0.010583622381091118, -0.005967772100120783, 0.030870184302330017, 0.006570343393832445, -0.014600763097405434, 0.04737136512994766, 0.0037313061766326427, 0.017629070207476616, -0.01901961863040924, -0.000830949516966939, -0.04208727926015854, -0.01349604967981577, 9.759190288605168e-05, 0.02421100065112114, -0.015682300552725792, -0.01693379506468773, -0.03599976375699043, -0.002902770647779107, 0.029294230043888092, -0.01674838922917843, 0.00432615214958787, 0.0027250894345343113, 0.0038259406574070454, -0.0342693030834198, -0.02107454091310501, -0.0017970913322642446, -0.0003852979280054569, 0.04171646758913994, -0.02421100065112114, -0.012399060651659966, 0.04641343280673027, -0.053180769085884094, -0.0047935307957232, -0.009880621917545795, -0.0027907544281333685, 0.016686586663126945, -0.001634860527701676, 0.00038095246418379247, 0.017644520848989487, 0.023144913837313652, -0.03170451521873474, -0.006945019122213125, 0.023376671597361565, 0.031380053609609604, -0.004445893689990044, -0.021553507074713707, 0.02852170169353485, -0.01135614886879921, 0.022418737411499023, 0.006775062996894121, -0.040913037955760956, 0.03936798498034477, 0.01659388281404972, 0.021831616759300232, -0.04227268695831299, 0.042025476694107056, -0.003115215804427862, -0.008211963810026646, 0.012344983406364918, 0.0014678016304969788, -0.014469433575868607, 0.02886161394417286, -0.01258446741849184, -0.04625892639160156, 0.009834270924329758, 0.049472637474536896, -0.005820991937071085, -0.003090108511969447, -0.012190478853881359, -0.008613677695393562, -0.01903506927192211, -0.010452291928231716, 0.015504620037972927, -0.000946828571613878, -0.01656298153102398, 

In [17]:
def get_embedding(text, model="text-embedding-3-small"):
    response = openai.embeddings.create(
        input = text,
        model = model,
    )
    return response.data[0].embedding

### Create Qdrant Collection
Remember to add these libraries at the top and add the qdrant client to pyproject.toml

uv add qdrant-client  

from qdrant_client import QdrantClient  
from qdrant_client.models import Distance, VectorParams, PointStruct

In [18]:
qdrant_client = QdrantClient(url="http://localhost:6333")

In [19]:
qdrant_client.create_collection(
    collection_name="Amazon-items-collection-00",
    vectors_config=VectorParams(size=1536, distance=Distance.COSINE),
)

True

### Embed data

Test

In [20]:
pointstruct = PointStruct(
    id = 0,
    vector = get_embedding("Test text"),
    payload={
        "text": "Test text",
        "model": "text-embedding-3-small",
    }
)

In [21]:
pointstruct

PointStruct(id=0, vector=[-0.020057253539562225, 0.006970119196921587, 0.037700485438108444, -0.040323127061128616, -0.01916317082941532, -0.0343029722571373, 0.0005480913096107543, -0.02425944246351719, 0.03871377930045128, 0.0015953787369653583, 0.030667034909129143, 0.012792832218110561, -0.010863103903830051, 0.011287793517112732, 0.02639034017920494, 0.04303517937660217, -0.046820126473903656, -0.00690678833052516, -0.02174110896885395, 0.05108192190527916, 0.0070856050588190556, 0.013113211840391159, 0.01130269467830658, -0.032544609159231186, -0.00393396383151412, -0.039041608572006226, -0.036955416202545166, 0.004965884145349264, 0.05841339752078056, -0.07462609559297562, 0.031382299959659576, -0.044018667191267014, -0.00025891143013723195, -0.010974864475429058, 0.006005255039781332, 0.03814752772450447, 0.03030940145254135, 0.037640880793333054, 0.010274499654769897, -0.029355714097619057, -0.014916278421878815, -0.010386260226368904, 0.021279167383909225, 0.018149876967072487, 0.02658405713737011, 0.008940826170146465, -0.011861496604979038, 0.008814164437353611, 0.019952943548560143, 0.03790910542011261, -0.03635936230421066, 0.01072154100984335, 0.0180604699999094, 0.017240893095731735, 0.02229246124625206, -0.0006305145216174424, -0.046998944133520126, 0.04071056470274925, -0.003473883494734764, -0.0003019857394974679, 0.024423357099294662, 0.01543782651424408, 0.006545430049300194, 0.006917964201420546, -0.0054390025325119495, -0.003609858686104417, 0.011466610245406628, 0.011593271978199482, -0.003455256810411811, -0.0030976238194853067, 0.0290874894708395, 0.015288813039660454, -0.05382377654314041, 0.001580477342940867, -0.04842947795987129, -0.007882828824222088, -0.004086702596396208, 0.045657820999622345, -0.025675073266029358, -0.0035912320017814636, 0.03278303146362305, 0.0303243026137352, -0.012330889701843262, -0.02291831746697426, -0.04640289023518562, 0.029191797599196434, -0.12660209834575653, -0.0037607350386679173, -0.009738050401210785, -0.06282420456409454, -0.005912121385335922, -0.03239559382200241, -0.0029448845889419317, -0.009469824843108654, 0.039667464792728424, -0.03376651927828789, -0.011652876622974873, -0.002326477551832795, -0.016212698072195053, 0.004280420485883951, 0.02738873101770878, 0.0030119409784674644, -0.011585820466279984, 0.02020626701414585, 0.007778518833220005, 0.03939924016594887, 0.01347084529697895, -0.008136152289807796, -0.03260421380400658, 0.017121681943535805, -0.04079997166991234, -0.02008705586194992, 0.0001558823714731261, -0.02217325009405613, 0.009633740410208702, -0.018820440396666527, 0.075937420129776, -0.08040783554315567, 0.0001582107215654105, -0.054598648101091385, 0.021592095494270325, 0.008858868852257729, 0.022992825135588646, -0.028804361820220947, -0.0023395163007080555, -0.06240696832537651, -0.004224540665745735, -0.07528176158666611, -0.022858712822198868, 0.013664563186466694, 0.014774715527892113, -0.01292694453150034, 0.022277558222413063, 0.038982003927230835, -0.05617819353938103, 0.04282655939459801, -0.037581272423267365, 0.018045568838715553, -0.04974079877138138, 0.05936708673834801, -0.03290224075317383, 0.024095527827739716, 0.0009448404307477176, 0.001196766854263842, -0.01142190583050251, -0.050873301923274994, -0.03287243843078613, 0.004366103559732437, 0.032127369195222855, 0.02957923337817192, -0.024453159421682358, 0.021279167383909225, -0.03928003087639809, 0.002196090528741479, 0.028804361820220947, -0.01181679219007492, -0.0023581429850310087, 0.005275087431073189, -0.01460334938019514, -0.05364495888352394, 0.019744325429201126, -0.02020626701414585, 0.0416344478726387, 0.016451120376586914, -0.02652445249259472, 0.0074655902571976185, 0.0266436617821455, -0.02761225216090679, -0.04544920101761818, 0.021711306646466255, 0.018269088119268417, -0.016808753833174706, -0.02965374104678631, -0.0018421828281134367, -0.04056154936552048, 0.0026543077547103167, 0.009015332907438278, 0.015616643242537975, -0.013381436467170715, 0.027299324050545692, 0.015765657648444176, 0.045896243304014206, 0.01411905512213707, 0.019997648894786835, -0.0055395872332155704, -0.013105761259794235, 0.04330340400338173, 0.024944905191659927, -0.01145915873348713, 0.005684875417500734, -0.0147002087906003, -0.01691306382417679, 0.03835614398121834, 0.01344104204326868, -0.007391083054244518, -0.057727936655282974, 0.05769813433289528, -0.016212698072195053, -0.04172385483980179, 0.03740245848894119, 0.021055646240711212, 0.024527667090296745, -0.00802439171820879, 0.011123877950012684, -0.015631545335054398, -0.0030380182433873415, -0.05936708673834801, 0.02652445249259472, -0.015780558809638023, -0.04035292938351631, 0.08213639259338379, -0.015720952302217484, -0.009037685580551624, -0.025198228657245636, -0.018045568838715553, -0.024602174758911133, -0.016942866146564484, 0.0003527435474097729, 0.046879734843969345, 0.016153093427419662, 0.0029635115060955286, 0.027820872142910957, 0.0722418799996376, 0.005424101371318102, 0.0035092744510620832, 0.0465519018471241, 0.028774559497833252, 0.006310733500868082, -0.013597507029771805, -0.055284108966588974, -0.004910003859549761, 0.004906278569251299, 0.01374652050435543, -0.01750911772251129, 0.028163602575659752, 0.0009276107302866876, -0.020429788157343864, 0.01558684092015028, -0.02804439142346382, 0.015184503048658371, -0.07617583870887756, 0.002283636014908552, 0.011123877950012684, 0.02695659175515175, 0.01971452310681343, -0.012636368162930012, 0.0017658132128417492, -0.04294576868414879, 0.039965495467185974, -0.01022979523986578, 0.02853613719344139, -0.00613936735317111, -0.016018981114029884, -0.033468492329120636, 0.01022979523986578, -0.0028647896833717823, 0.0021402102429419756, 0.008106349036097527, 0.038922399282455444, -0.006236226297914982, -0.047744013369083405, -0.024646878242492676, -0.05352574586868286, -0.03621034696698189, -0.026137016713619232, 0.011906200088560581, 0.055760953575372696, -0.03179953992366791, 0.006731697358191013, -0.07194384932518005, -0.0020023726392537355, 0.010691738687455654, 0.06568527221679688, -0.0006300488603301346, -0.03933963552117348, 0.04613466560840607, -0.02798478677868843, -0.022754402831196785, 0.005249009933322668, 0.03951845318078995, -0.04851888492703438, -0.002771656261757016, -0.03853496164083481, 0.00019069106201641262, -0.011272892355918884, -0.005826438311487436, -0.002505294047296047, -0.017658133059740067, 0.002015411388128996, 0.0489957295358181, -0.004433159716427326, -0.03147171065211296, 0.05054547265172005, -0.004343751352280378, -0.00017427626880817115, 0.029847458004951477, 0.001356956665404141, -0.009723148308694363, -0.0003485525376163423, -0.009141994640231133, 0.04196227714419365, 0.03546527773141861, 0.02431904710829258, 0.010483118705451488, -0.004179836250841618, 0.012293635867536068, 0.014007294550538063, -0.015571939758956432, 0.008091447874903679, -0.01764323003590107, 0.016004079952836037, 0.05075409263372421, 0.010848202742636204, -0.03269362077116966, -0.027791067957878113, -0.05641661584377289, 0.004679032601416111, 0.022501079365611076, 0.026137016713619232, -0.04917454347014427, 0.03993568941950798, -0.0336771123111248, 0.04494255408644676, 0.024900201708078384, -0.011742285452783108, 0.020101958885788918, 0.018582018092274666, -0.020608603954315186, 0.0343029722571373, 0.017375005409121513, -0.05373436585068703, -0.010185091756284237, 0.009484726935625076, -0.03510764613747597, 0.028506334871053696, 0.011161131784319878, 0.013411239720880985, 0.07671228796243668, 0.024706482887268066, 0.05805576592683792, -0.026315832510590553, 0.02485549822449684, -0.013642210513353348, -0.012561861425638199, 0.03933963552117348, 0.0015367044834420085, -0.003911611624062061, 0.03603152930736542, 0.05951610207557678, 0.02247127704322338, -0.013403789140284061, 0.004343751352280378, 0.035524882376194, -0.015571939758956432, 0.06359907984733582, -0.05310850962996483, -0.046939339488744736, 0.023112036287784576, 0.027046000584959984, -0.014059449546039104, 0.029907064512372017, 0.017926357686519623, 0.02536214329302311, 0.030398810282349586, 0.027418535202741623, 0.028223209083080292, -0.03475001081824303, 0.009492177516222, -0.005927023012191057, 0.004582173656672239, -0.013090860098600388, 0.03916081786155701, 0.02412533015012741, 0.009492177516222, -0.05072428658604622, 0.008769460953772068, -0.021636798977851868, 0.02774636447429657, 0.03343869000673294, 0.03117368184030056, -0.029296107590198517, 0.02203913778066635, 0.007134034298360348, -0.033349283039569855, 0.035495080053806305, 0.002961648628115654, 0.011772087775170803, 0.03618054464459419, -0.026122113689780235, 0.010006275027990341, 0.05567154660820961, 0.016555430367588997, -0.01831379346549511, 0.01677895151078701, 0.013798675499856472, 0.029549431055784225, -0.008560840971767902, 0.057727936655282974, 0.02272460050880909, 0.00152366585098207, 0.05582055822014809, -0.03913101553916931, -0.05167797580361366, 0.004064350854605436, -0.029445121064782143, 0.007432061713188887, -0.017717737704515457, 0.02457237057387829, 0.010870554484426975, -0.04720756411552429, 0.03773028776049614, 0.0027902829460799694, 0.03123328648507595, -0.00479079270735383, -0.015974275767803192, 0.01458099763840437, 0.05409200116991997, 0.055880166590213776, 0.017181288450956345, 0.020161563530564308, -0.034451983869075775, -0.008739657700061798, -0.01295674778521061, -0.020593702793121338, -0.006269754376262426, 0.03641896694898605, 0.04512137174606323, -0.010147837921977043, 0.0033695739693939686, -0.016138192266225815, -0.022709699347615242, 0.007778518833220005, -0.02719501405954361, 0.03361750766634941, -0.03841575235128403, -0.005360770504921675, -0.012241481803357601, 0.04330340400338173, -0.014536293223500252, -0.01393278781324625, -0.01046821754425764, 0.005811537150293589, -0.007733814883977175, -0.0012647544499486685, -0.03576330468058586, 0.021830517798662186, 0.006660915445536375, 0.0023637309204787016, 0.002661758568137884, -0.03284263610839844, -0.02573467791080475, -0.04491275176405907, -0.0049919611774384975, -0.05579075589776039, 0.009134544059634209, -0.0275526475161314, 0.018269088119268417, 0.02203913778066635, 0.03117368184030056, 0.015318616293370724, -0.001533910515718162, -0.015706051141023636, -0.012435199692845345, 0.030428612604737282, -0.006228775717318058, -0.02308223396539688, 0.054419830441474915, 0.04023372009396553, 0.05841339752078056, -0.026613859459757805, -0.025436650961637497, -0.0028610643930733204, -0.00023178626724984497, -0.014662954956293106, 0.01874593272805214, -0.024035921320319176, 0.016212698072195053, -0.010408611968159676, -0.03576330468058586, -0.037760090082883835, 0.013783774338662624, -0.01984863542020321, -0.04267754405736923, 0.004217089619487524, -0.020176464691758156, 0.157954603433609, -0.033587705343961716, 0.006329359952360392, -0.001464991713874042, -0.033587705343961716, -0.04369083791971207, 0.01665974035859108, 0.0066273873671889305, -0.01868632808327675, 0.008367123082280159, -0.005986628122627735, 0.05918826907873154, -0.008285165764391422, 0.01555703766644001, -0.054419830441474915, -0.010706639848649502, 0.006500725634396076, -0.030667034909129143, 0.023439867421984673, 0.05474765971302986, 0.005826438311487436, -0.006869534961879253, -0.000662179954815656, 0.02707580290734768, -0.00230412557721138, -0.0032112468034029007, 0.010334105230867863, -0.002199815819039941, 0.0006705619744025171, -0.016689542680978775, 0.012502255849540234, -0.015273911878466606, 0.017956160008907318, -0.015109996311366558, -0.007778518833220005, 0.0001378377346554771, 0.022426573559641838, -0.013597507029771805, -0.012286185286939144, -0.02075761929154396, -0.04607505723834038, -0.03409435227513313, -0.05009843036532402, 0.006280930712819099, -0.006172895431518555, -0.004787067417055368, 0.006646014284342527, 0.06467197835445404, -0.016495823860168457, -0.024021020159125328, -0.043571628630161285, -0.00964864157140255, 0.020042352378368378, 0.02309713512659073, -0.013947688974440098, 0.030905457213521004, 0.018269088119268417, 0.02504921518266201, -0.00848633423447609, -0.013098310679197311, 0.03153131529688835, -0.008054194040596485, 0.008903573267161846, -0.014662954956293106, -0.0038259285502135754, 0.01691306382417679, -0.042290110141038895, 0.016868358477950096, 0.010594879277050495, 0.031382299959659576, 0.011436806991696358, 0.007040900643914938, 0.004101604223251343, -0.0029039059299975634, -0.0039600408636033535, 0.0030957611743360758, -0.011690130457282066, 0.015072743408381939, -0.03197835758328438, -0.024766089394688606, 0.021145055070519447, -0.027105605229735374, -0.01581036113202572, 0.049263954162597656, 0.013597507029771805, -0.007208541501313448, 0.02928120642900467, -0.035435475409030914, -0.015132348984479904, -0.01671934500336647, -0.002039626007899642, 0.013448492623865604, -0.003563291858881712, -0.021711306646466255, 0.014282969757914543, 0.004556096158921719, 0.005692325998097658, 0.015616643242537975, 0.04038273170590401, -0.0385945662856102, -0.0023171640932559967, 0.017225991934537888, -0.021756010130047798, -0.02266499400138855, 0.01677895151078701, 0.06198972836136818, -0.00590839609503746, 0.031322695314884186, 0.015072743408381939, -0.011101526208221912, -0.026479747146368027, 0.017240893095731735, -0.04172385483980179, -0.03472020849585533, 0.0033043804578483105, 0.03173993527889252, -0.011503863148391247, 0.028521236032247543, -0.004239441826939583, 0.014506490901112556, 0.034690406173467636, -0.0104160625487566, 0.01630210690200329, -0.007823223248124123, -0.026569155976176262, -0.0180604699999094, -0.007875378243625164, -0.019431395456194878, -0.023365359753370285, -0.0011567194014787674, 0.010460766963660717, -0.009596486575901508, -0.005427826661616564, 0.01381357666105032, -0.009201600216329098, -0.024229640141129494, -0.014797067269682884, -0.0025015687569975853, 0.01555703766644001, -0.02156229317188263, 0.007279322948306799, 0.00621387455612421, 0.0195953119546175, 0.004749814048409462, -0.003177718725055456, 0.0016307694604620337, 0.026196621358394623, 0.02278420515358448, -0.014692758210003376, -0.03698521852493286, -0.0199082400649786, 0.04038273170590401, 0.03847535699605942, -0.03546527773141861, 0.012196777388453484, 0.024289244785904884, 0.030845850706100464, 0.010512921959161758, -0.008620446547865868, 0.03331948071718216, 0.011556018143892288, 0.02431904710829258, 0.010505471378564835, -0.0005415719351731241, -0.016317008063197136, -0.013523000292479992, 0.021145055070519447, -0.0007641612319275737, -0.005405474454164505, 0.029057685285806656, -0.010050979442894459, -0.052572060376405716, -0.042528532445430756, -0.003829654073342681, -0.0007995520136319101, 0.007588526234030724, 0.021606996655464172, -0.01746441423892975, -0.023812400177121162, -0.015065292827785015, 0.016942866146564484, -0.045479003340005875, -0.014245716854929924, -0.011854046024382114, 0.003492510411888361, -0.004243167117238045, 0.018462806940078735, 0.01630210690200329, -0.009112192317843437, 0.04276695474982262, 0.04848908260464668, 0.023231247439980507, -0.07242069393396378, -0.005003137513995171, 0.017345203086733818, 0.00502176396548748, 0.004831771831959486, -0.022694798186421394, -0.03603152930736542, 0.007525195367634296, 0.013880632817745209, 0.006221325136721134, 0.02045959047973156, 0.005178228486329317, -0.030398810282349586, -0.044733934104442596, -0.04604525491595268, 0.01782204769551754, 0.007704012095928192, 0.0247958917170763, -0.027701660990715027, 0.004667856264859438, 0.0010104996617883444, -0.015571939758956432, -0.05841339752078056, 0.015646446496248245, -0.014029646292328835, -0.019133368507027626, 0.005062743090093136, 0.008680052123963833, -0.04667111486196518, -0.014841771684587002, -0.0049211797304451466, 0.05108192190527916, 0.004801969043910503, 0.0006915170233696699, -0.007577350363135338, -0.028700051829218864, -0.032365791499614716, 0.01004352793097496, 0.017240893095731735, -0.01971452310681343, -0.01916317082941532, 0.014811969362199306, -0.030845850706100464, -0.005059017799794674, 0.03454139083623886, 0.014059449546039104, -0.022873613983392715, 0.0005015244823880494, -0.04929375648498535, 0.024602174758911133, -0.0033285950776189566, 0.020161563530564308, 0.022441474720835686, 0.016078585758805275, 0.0018980628810822964, 0.023842204362154007, 0.0014156308025121689, 0.0037905378267169, -0.020444689318537712, -0.02670326828956604, -0.01099721621721983, 0.013113211840391159, -0.012964198365807533, -0.033289678394794464, -0.01399984396994114, 0.017166387289762497, 0.011079174466431141, -0.03325987234711647, 0.022635191679000854, 0.00453374395146966, 0.020072154700756073, -0.019133368507027626, -0.024050822481513023, -0.02254578471183777, 0.014342575334012508, -0.01585506461560726, -0.008612995967268944, -0.021964630112051964, -0.04273714870214462, 0.00451511749997735, 0.006806204095482826, 0.04214109480381012, 0.07093055546283722, 0.003963766153901815, 0.026628760620951653, -0.015780558809638023, -0.009872162714600563, -0.04813144728541374, -0.00595682580024004, 0.024289244785904884, 0.015318616293370724, 0.026539353653788567, 0.029102390632033348, -0.0075214700773358345, -0.015542136505246162, 0.016063684597611427, 0.003317419206723571, 0.015422925353050232, -0.044733934104442596, -0.05748951435089111, 0.03504803776741028, 0.017136583104729652, 0.01014038734138012, -0.01904395967721939, 0.00586369214579463, -0.033289678394794464, 0.009745500981807709, -0.021085448563098907, -0.006228775717318058, 0.01862672157585621, 0.035673897713422775, -0.044257089495658875, -0.03221677616238594, 0.0009667268604971468, -0.023544175550341606, 0.008627897128462791, 0.04047214239835739, -0.004541194532066584, -0.0020060979295521975, -0.02217325009405613, -0.06586408615112305, 0.00142401282209903, -0.034273166209459305, -0.026539353653788567, -0.015378221869468689, 0.006206423509865999, 0.012137171812355518, 0.04178346320986748, -0.015691149979829788, -0.0076034278608858585, 0.029862361028790474, -0.019625114277005196, -0.015452728606760502, 0.01916317082941532, -0.0009685895056463778, -0.004686483182013035, 0.013448492623865604, -0.005673699546605349, -0.02780597098171711, -0.031382299959659576, -0.02859574370086193, 0.005152150988578796, 0.008717305958271027, 0.010036077350378036, -0.036895811557769775, -0.010594879277050495, -0.015959374606609344, -0.0016754736425355077, 0.004030822776257992, -0.0009508941438980401, 0.008151053451001644, 0.00779342046007514, 0.0300113745033741, 0.013761421665549278, -0.01685345731675625, -0.0017155210953205824, -0.01721109077334404, 0.0008987393230199814, 0.022396769374608994, -0.03287243843078613, -0.025257835164666176, -0.009626289829611778, -0.005640171468257904, 0.02799968793988228, 0.005975452251732349, 0.02577938325703144, 0.018283989280462265, 0.01905886083841324, 0.0005392435705289245, -0.0076891109347343445, 0.013068508356809616, -0.008843967691063881, 0.032425396144390106, 0.025019412860274315, -0.0033230071421712637, 0.04127681627869606, -0.013150465674698353, 0.007882828824222088, -0.012934395112097263, 0.03466060385107994, 0.003157229395583272, -0.01579545997083187, -0.011690130457282066, -0.010885456576943398, -0.01420846302062273, -0.022098742425441742, -0.036299753934144974, 0.05909886211156845, 0.016689542680978775, -0.02284381166100502, 0.007651857100427151, 0.02969844453036785, -0.002598427701741457, 0.0008344771340489388, -0.0026394063606858253, -0.03680640086531639, 0.01016273908317089, 0.019610213115811348, 0.016734246164560318, 0.013373985886573792, 0.006545430049300194, 0.013284577988088131, 0.04312458634376526, 0.020981138572096825, 0.013835928402841091, 0.006854633800685406, 0.029236502945423126, -0.015631545335054398, 0.003915336914360523, 0.00744323804974556, 0.043392810970544815, 0.00430277269333601, 0.007260696031153202, 0.01892474852502346, -0.01862672157585621, -0.0060462336987257, -0.014163759537041187, -0.030279599130153656, 0.008843967691063881, 0.003539077006280422, -0.004179836250841618, 0.001991196535527706, 0.01215952355

##### Amazon data

In [22]:
pointstructs = []
for i, data in enumerate(data_to_embed):
    embedding = get_embedding(data["description"])
    pointstructs.append(
        PointStruct(
            id=i,
            vector=embedding,
            payload=data,
        )
    )

In [23]:
pointstructs

[PointStruct(id=0, vector=[0.010930042713880539, -0.015056160278618336, 0.01137808058410883, -0.011284304782748222, -0.0503886416554451, -0.0004936232580803335, -0.03859378397464752, 0.04171963036060333, 0.002547564683482051, -0.010346551425755024, -0.0291745662689209, 0.014462249353528023, -0.03096671774983406, 0.08677349239587784, 0.01424343977123499, 0.004819013178348541, -0.03596807271242142, 0.009127471596002579, -0.018807174637913704, 0.016889989376068115, 0.01028924435377121, 0.0174943208694458, 0.033800818026065826, 0.03059161640703678, 0.021776730194687843, 0.02110988274216652, -0.03313397243618965, -0.026548855006694794, -0.023027068004012108, 0.05222247168421745, -0.013222330249845982, -0.020338840782642365, -0.01941150613129139, -0.049179982393980026, -0.04113613814115524, -0.019265633076429367, -0.017202574759721756, 0.01579594425857067, -0.018254943192005157, 0.0005453950725495815, 0.024214889854192734, 0.04019838199019432, 0.00795527920126915, 0.0011038144584745169, -0.005241002421826124, 0.00922645628452301, -0.0021542292088270187, 0.019276052713394165, 0.0006570789264515042, 0.01994290016591549, 0.0023131263442337513, 0.044512052088975906, -0.00636630691587925, 0.053806234151124954, -0.02725737914443016, 0.005657781846821308, -0.0153791643679142, -0.006439243443310261, 0.030424904078245163, 0.014493507333099842, 0.021714212372899055, -0.04317835718393326, -0.0021399022080004215, 0.02275616116821766, -0.036301493644714355, 0.02079729735851288, -0.029132887721061707, 0.02852855809032917, -0.020964009687304497, 0.015775104984641075, 0.018286200240254402, -0.021651696413755417, -0.01729634962975979, -0.007095671258866787, 0.06022464111447334, 0.0169629268348217, 0.019911641255021095, -0.01750473864376545, -0.048221390694379807, 0.059849537909030914, 0.009434846229851246, 0.006168336607515812, -0.02567361854016781, -0.004584574606269598, -0.03405088558793068, -0.010320502333343029, -0.036718275398015976, -0.061016518622636795, -0.046846017241477966, -0.0008674223790876567, -0.03594723343849182, -0.03840623050928116, 0.027965905144810677, -0.019661573693156242, -0.011742762289941311, 0.027007311582565308, -0.0010823243064805865, -0.06610123068094254, -0.015493778511881828, 0.030695810914039612, 0.007418675348162651, 0.029299600049853325, -0.06543438136577606, 0.019484441727399826, 0.002546262228861451, 0.033384039998054504, -0.03265467286109924, 0.030216515064239502, 0.014681058004498482, 0.05639026686549187, -0.0386979766190052, -0.018213264644145966, -0.015076998621225357, 0.025840329006314278, 0.025861168280243874, -0.02715318463742733, 0.0551399290561676, -0.013982952572405338, -0.004902368877083063, -0.03217537701129913, -0.04044845327734947, 0.037572674453258514, 0.03888553008437157, -0.000531393860001117, -0.01728592999279499, -0.00975785031914711, -0.03188363090157509, -0.05626523494720459, 0.013805821537971497, 0.007418675348162651, 0.006064142100512981, 0.015535456128418446, 0.046804338693618774, -0.012597160413861275, 0.015670910477638245, 0.016619082540273666, -0.029945608228445053, 0.0015629231929779053, 0.027111507952213287, -0.028382685035467148, 0.02698647417128086, -0.01894262805581093, -0.016629502177238464, 0.013086876831948757, -0.04459540918469429, -0.0012425238965079188, 0.032112862914800644, 0.014910287223756313, 0.015004062093794346, 0.007460353430360556, -0.004149560816586018, 0.03082084469497204, 0.01924479380249977, -0.00814282987266779, 0.02290203422307968, 0.014045469462871552, 0.05580677464604378, 0.05018025264143944, -0.02921624295413494, 0.026590533554553986, 0.005642152391374111, 0.027069829404354095, -0.0072102854028344154, -0.049138303846120834, 0.011065496131777763, 0.06635129451751709, -0.038114484399557114, -0.02083897590637207, -0.04405359551310539, -0.023402169346809387, -0.005980785936117172, -0.0044308872893452644, -0.030570777133107185, 0.05922436714172363, 0.018202845007181168, -0.04301164671778679, -0.015733426436781883, 0.02498593181371689, -0.008606497198343277, 0.01675453595817089, 0.005855752155184746, 0.01818200573325157, -0.010096483863890171, 0.04201137647032738, 0.01968241296708584, 0.018786337226629257, -0.006449663080275059, 0.0036025377921760082, -0.024277405813336372, 0.005201929248869419, 0.04626252502202988, -0.03413424268364906, -0.017108798027038574, 0.011180110275745392, -0.012180381454527378, -0.01352449506521225, 0.044470373541116714, -0.020140869542956352, -0.06876862049102783, -0.04007335007190704, 0.022610288113355637, 0.022339381277561188, 0.031112590804696083, 0.011503114365041256, 0.007356158457696438, 0.04422030597925186, 0.0007293641683645546, -0.016191884875297546, 0.010773750022053719, -0.03600975126028061, 0.036405690014362335, -0.034655217081308365, -0.01386833842843771, -0.0025032819248735905, 0.0169629268348217, -0.03011232055723667, 0.005308729130774736, 0.023256296291947365, -0.005949527490884066, 0.0673098936676979, -0.0822305977344513, -0.031633563339710236, 0.04763789847493172, 0.03665575757622719, -0.021297432482242584, 0.0020409170538187027, 0.0445537306368351, -0.026757244020700455, -0.04392855986952782, -0.04113613814115524, -0.039052240550518036, 0.03261299803853035, 0.019369827583432198, 0.018588365986943245, 0.05397294834256172, -0.03532206267118454, 0.01371204573661089, -0.015149935148656368, -0.021880924701690674, -0.02619459293782711, 0.025631939992308617, 0.03223789483308792, -0.0837726816534996, 0.020870234817266464, 0.0214849840849638, -0.027778353542089462, -0.019474022090435028, -0.0019028589595109224, 0.039114758372306824, -0.04024006053805351, 0.05497321859002113, 0.024319084361195564, 0.06489256769418716, -0.013982952572405338, 0.010257985442876816, 0.02636130340397358, 0.05097213387489319, 0.008335590362548828, 0.032904744148254395, 0.023402169346809387, -0.01623356156051159, 0.0038083228282630444, 0.0048711104318499565, -0.04153207689523697, 0.02110988274216652, -0.0014274697750806808, -0.02196427993476391, 0.026423821225762367, 0.019599055871367455, 0.015264549292623997, 0.03150853142142296, 0.057682283222675323, -0.028882820159196854, -0.008007376454770565, -0.018432073295116425, 0.011419758200645447, -0.033425718545913696, 0.04021922126412392, -0.037635188549757004, 0.00816366821527481, 0.01434763427823782, -0.017327608540654182, 0.016712859272956848, 0.0006108424859121442, -0.010570569895207882, 0.01503532100468874, -0.008731530979275703, -0.0014639380387961864, -0.015024901367723942, -0.04236563667654991, 0.07722924649715424, -0.046846017241477966, 0.023902304470539093, -0.020724361762404442, 0.04501218721270561, 0.010086064226925373, -0.009809947572648525, 0.004441306460648775, 0.012899326160550117, -0.0036702645011246204, 0.018630044534802437, -0.012774292379617691, 0.013138974085450172, -0.022464415058493614, 0.004329297225922346, 0.038156162947416306, -0.04007335007190704, -0.02773667685687542, -0.018682140856981277, -0.027590803802013397, -0.01919269561767578, 0.024631669744849205, 0.062225181609392166, -0.05551503226161003, -0.0020995268132537603, 0.006522599142044783, 0.017171315848827362, -0.04926333948969841, -0.03882301226258278, -0.04092774912714958, 0.05739053711295128, -0.039698246866464615, -0.019984576851129532, -0.01601475290954113, 0.05680704861879349, 0.011992830783128738, -0.03196698799729347, 0.04040677472949028, 0.04842977970838547, 0.010044386610388756, 0.02471502497792244, -0.03721841052174568, -0.010466375388205051, 7.053504668874666e-05, 0.007700001355260611, -0.009132681414484978, -0.02025548368692398, -0.030695810914039612, -0.030466582626104355, 0.02581949159502983, 0.03928146883845329, 0.006449663080275059, -0.026007041335105896, -0.039594054222106934, 0.010086064226925373, -0.06597619503736496, -0.006012044381350279, 0.004647091496735811, 0.03198782727122307, 0.02365223690867424, 0.015212452039122581, 0.024089856073260307, 0.008054263889789581, -0.007231124676764011, 0.03694750368595123, 0.017306769266724586, 0.04676266014575958, 0.006777876988053322, -0.025798652321100235, 0.02079729735851288, 0.00326911429874599, 0.014910287223756313, -0.0071321395225822926, -0.036718275398015976, -0.02323545701801777, 0.025902846828103065, -0.040761034935712814, -0.008929501287639141, -0.020380517467856407, -0.02344384789466858, -0.0007625762373209, 0.045053865760564804, 0.007668742910027504, 0.04538729041814804, -0.02986225113272667, 0.007449933793395758, -0.001414445461705327, 0.021568339318037033, -0.015660490840673447, -0.013461978174746037, -0.00572550855576992, -0.022047637030482292, 0.018390396609902382, -0.021818406879901886, 0.011044656857848167, 0.016556566581130028, -0.01745264232158661, -0.003545230720192194, 0.023839788511395454, 0.06172504648566246, 0.05805738642811775, -0.007772937882691622, 0.007684372365474701, -0.06543438136577606, 0.07397836446762085, 0.06014128401875496, -0.0519724041223526, -0.008028215728700161, 0.016848310828208923, 0.01941150613129139, -0.0230687465518713, -0.06039135158061981, 0.008273073472082615, 0.038093648850917816, -0.004634066950529814, -0.04597077891230583, 0.029341276735067368, -0.008231394924223423, 0.06426739692687988, 0.023089583963155746, 0.017483901232481003, 0.0006277741631492972, -0.003896888345479965, 0.005944317672401667, 0.06664304435253143, 0.009023276157677174, 0.016296079382300377, 0.05447308346629143, 0.0710609033703804, -0.011232207529246807, -0.022631127387285233, -0.04251151159405708, -0.04284493252635002, -0.009606767445802689, -0.03803113102912903, -0.03867713734507561, 0.002922666259109974, 0.01994290016591549, 0.0418863408267498, -0.03848958760499954, -0.0005040427204221487, 0.04009418934583664, 0.007189446594566107, -0.022568609565496445, -0.05193072557449341, -0.02296455018222332, -0.052430860698223114, -0.020828556269407272, 0.01824452355504036, 0.01371204573661089, 0.008372058160603046, -0.015889719128608704, 0.03330068290233612, 0.010044386610388756, 0.019265633076429367, 0.012774292379617691, -0.055223286151885986, 0.018338298425078392, -0.04809635505080223, -0.022881194949150085, -0.0822305977344513, 0.06226686015725136, -0.036197301000356674, 0.062016792595386505, 0.018390396609902382, 0.0020422195084393024, 0.020547229796648026, -0.029299600049853325, -0.009632816538214684, 1.1375964277249295e-05, 0.01548335887491703, 0.02979973517358303, 0.0028080518823117018, -0.0291745662689209, 0.00832517072558403, 0.030987557023763657, 0.028674431145191193, 0.07297809422016144, -0.013555753976106644, -0.03876049444079399, 0.04009418934583664, 0.0159001387655735, -0.019661573693156242, 0.02990392968058586, -0.010711233131587505, 0.024527473375201225, 0.018900951370596886, -0.0025931501295417547, 0.012878486886620522, 0.001616323017515242, -0.026007041335105896, 0.007835455238819122, -0.007278012111783028, 0.00888782273977995, 0.0044100480154156685, 0.02646549977362156, 0.01929689198732376, -0.0005209743976593018, -0.04755454137921333, 8.921686094254255e-05, -0.04326171427965164, -0.0014808697160333395, -0.004449121188372374, -0.005720298737287521, 0.03257131949067116, 0.03473857045173645, -0.008158459328114986, 0.007762518245726824, -0.04024006053805351, 0.03313397243618965, 0.013962113298475742, 0.004269385244697332, 0.006663262378424406, 0.0418863408267498, 0.002528028329834342, 0.059682827442884445, 0.03165440261363983, 0.03271719068288803, 0.01153437327593565, 0.006876862142235041, 0.002160741249099374, -0.003441035747528076, -0.0159105584025383, -0.0018221079371869564, -0.012440868653357029, -8.2297672634013e-05, 0.04263654351234436, 0.033008936792612076, -0.0014027234865352511, 0.00017240995657630265, 0.03250880166888237, -0.007340529002249241, 0.033800818026065826, -0.026132075116038322, 0.0023248482029885054, -0.010028757154941559, -0.016421113163232803, -0.0413653664290905, -0.06810177117586136, -0.05451475828886032, -0.0022779605351388454, 0.012815969996154308, -0.030320709571242332, 0.0003643564705271274, 0.0030268612317740917, -0.005777605809271336, -0.007694791536778212, 0.03219621628522873, -0.00537124602124095, -0.003263904480263591, 0.033967528492212296, -0.01010169368237257, -0.0005887010484002531, 0.01103423722088337, -0.022318542003631592, 0.006595535669475794, 0.03240460529923439, 0.03936482593417168, 0.00024664882221259177, 0.06326712667942047, 0.01607726886868477, -0.024735864251852036, 0.044095274060964584, -0.010909203439950943, -0.002090409630909562, 0.04588742554187775, -0.021339111030101776, 0.03784358128905296, 0.054764825850725174, 0.03644736856222153, -0.006064142100512981, 0.01766103133559227, 0.01617104560136795, -0.022610288113355637, 0.002979973563924432, 0.030508259311318398, 0.019223954528570175, -0.03330068290233612, -0.019713670015335083, 0.006652842741459608, 0.010930042713880539, -0.004412652924656868, 0.029153726994991302, -0.052055761218070984, 0.04151123762130737, 0.025527745485305786, 0.017358867451548576, 0.011138432659208775, 0.00033863334101624787, 0.021307852119207382, -0.013107715174555779, 0.03140433505177498, 0.02381894923746586, 0.02932043932378292, -0.019526120275259018, -0.017192155122756958, 0.005704669747501612, -0.03463437780737877, 0.006574696861207485, 0.04405359551310539, -0.027799192816019058, -0.05218079313635826, -0.04199053719639778, 0.00920040812343359, -0.013795401901006699, 0.030424904078245163, 0.0025032819248735905, 0.024464957416057587, 0.0344885028898716, -0.01424343977123499, 0.005845332518219948, 0.016577405855059624, -0.012305415235459805, 0.00681434478610754, -0.027299057692289352, 0.021141139790415764, 0.028820302337408066, -0.019057242199778557, -0.002611384028568864, -0.0035009479615837336, -0.02921624295413494, 0.009934981353580952, 0.0032925582490861416, 0.03848958760499954, -0.011367660947144032, 0.019067661836743355, 0.022089313715696335, 0.014524766243994236, 0.03240460529923439, -0.02609039656817913, 0.012784711085259914, -0.01623356156051159, 0.01798403635621071, 0.012524223886430264, -0.007653113920241594, 0.006465292070060968, -0.024214889854192734, -0.016723277047276497, 0.006845603231340647, 0.02211015298962593, -0.0006333094788715243, -0.014774833805859089, 0.018994726240634918, 0.022631127387285233, -0.018473751842975616, -0.003430616343393922, 0.021234916523098946, 0.02540271170437336, 0.013607851229608059, -0.04130284860730171, -0.035822197794914246, 0.003550440538674593, 0.00866901408880949, -0.0047486815601587296, 0.01963031478226185, -0.01760893501341343, 0.028570234775543213, 0.010612248443067074, 0.002522818511351943, 0.01793193817138672, 0.02656969428062439, -0.03655156493186951, 0.04480379819869995, 0.01622314192354679, -0.0018481566803529859, 0.025902846828103065, -0.030320709571242332, 0.005238397512584925, 0.012034508399665356, -0.029945608228445053, -0.016587823629379272, 0.008705481886863708, -0.012315834872424603, -0.010575779713690281, -0.003701522946357727, -0.0349886417388916, 0.01894262805581093, -0.016671180725097656, 0.0023821552749723196, -0.030133157968521118, -0.004368370398879051, 0.00322222663089633, -0.003753620432689786, -0.0035087624564766884, -0.020984848961234093, -0.0028080518823117018, -0.011971991509199142, 0.0056108939461410046, 0.010643506422638893, -0.0036937084514647722, 0.011357241310179234, 0.006595535669475794, -0.051472268998622894, 0.015274968929588795, 0.02279783971607685, -0.0086221257224679, 0.0006284253322519362, -0.03598891198635101, 0.001281596953049302, -0.04057348519563675, 0.024860898032784462, 0.013253588229417801, 0.032425444573163986, -0.0032196217216551304, -0.036572400480508804, -0.0036937084514647722, 0.0003072120889555663, 0.011888635344803333, 0.005246212240308523, -0.011899054981768131, -0.03138349577784538, 0.0397607646882534, -0.008715901523828506, 0.009403587318956852, -0.012399190105497837, -0.025861168280243874, -0.020651424303650856, -0.008642964996397495, 0.026507176458835602, -0.0044204676523804665, 0.005397294647991657, 0.0016566985286772251, 0.022297704592347145, -0.009143100120127201, -0.0011539582628756762, -0.046637628227472305, 0.015181194059550762, 0.04555400088429451, -0.006460082251578569, -0.003740596119314432, 0.0022050240077078342, -0.02948714978992939, -0.0018989515956491232, -0.009825577028095722, -0.019922060891985893, -0.02709066867828369, -0.01940108649432659, -0.016212722286581993, -0.0030529098585247993, -0.0054650213569402695, -0.02577781304717064, -0.002027892740443349, 0.02206847444176674, 0.02859107404947281, 0.0312793031334877, 0.04676266014575958, 0.014795673079788685, -0.007694791536778212, -0.03388417512178421, -0.005673411302268505, -0.0365932397544384, -0.008955549448728561, -0.01548335887491703, 0.013899596408009529, 0.00438660429790616, 0.032633837312459946, -0.0006574045401066542, 0.03461353853344917, -0.005238397512584925, -0.011784440837800503, 0.014899867586791515, 0.004180819261819124, -0.003487923415377736, 0.027340736240148544, 0.011544791981577873, -0.022256026044487953, -0.03542625904083252, -0.014576863497495651, -0.017827743664383888, -0.011503114365041256, 0.04157375544309616, -0.007528080139309168, -0.02609039656817913, 0.040969427675008774, -0.001559015829116106, -0.0005408365395851433, -0.060849808156490326, -0.0005287890089675784, 0.02619459293782711, 0.055973488837480545, -0.005642152391374111, -0.03255048021674156, 0.03723924979567528, 0.01893220841884613, 0.011075915768742561, 0.004649696405977011, -0.01632733643054962, -0.011044656857848167, -0.02800758369266987, 0.007361368276178837, 0.0012216849718242884, -0.014816511422395706, -0.016889989376068115, 0.007449933793395758, 0.0006095400312915444, -0.021016106009483337, -0.027611643075942993, 0.010346551425755024, 0.009361909702420235, -0.0038604203145951033, 0.026903117075562477, 0.00027725606923922896, 0.023985661566257477, -0.032008666545152664, -0.010304873809218407, -0.019223954528570175, -0.03919811174273491, -0.05001354217529297, 0.006840393878519535, 0.0007358763250522316, 0.009158729575574398, -0.008189717307686806, 0.011461436748504639, -0.014889447949826717, 0.03265467286109924, 0.009851626120507717, -0.046804338693618774, 0.028299327939748764, 0.010086064226925373, -0.02152666263282299, -0.022464415058493614, -0.0018325274577364326, -0.020984848961234093, 0.032487962394952774, 0.03169608116149902, 0.00029060602537356317, 0.0025931501295417547, 0.01529580820351839, -0.004055785480886698, 0.005076895467936993, 0.015087418258190155, -0.039906639605760574, -0.02742409147322178, 0.006897700950503349, -0.006824764423072338, -0.019432345405220985, 0.003493133233860135, -0.016452372074127197, -0.03663491830229759, 0.0075593385845422745, 0.0003228413115721196, 0.02423572912812233, 0.022193508222699165, -0.013389041647315025, -0.005590055137872696, 0.03350907191634178, -0.008903452195227146, 0.02577781304717064, 0.0014509137254208326, -0.027340736240148544, 0.0028106567915529013, -0.022881194949150085, -0.0013362993486225605, 0.017535997554659843, 0.005704669747501612, -0.015973074361681938, 0.01119052991271019, 0.004261570516973734, 0.023902304470539093, 0.04288661107420921, -0.032321251928806305, 0.027715837582945824, -0.007012315094470978, 0.03776022419333458, 0.02859107404947281, -0.0310292337089777, 0.045637357980012894, -0.01495196484029293, 0.005584845319390297, -0.010575779713690281, -0.027278218418359756, 0.022818678990006447, -0.00021913484670221806, -0.01745264232158661, -0.05318106710910797, 0.00787192303687334, 0.0034827138297259808, -0.04555400088429451, 0.018286200240254402, 0.0015199427725747228, 0.0031102171633392572, -0.013003520667552948, -0.02258944883942604, -0.00047734277904964983, 0.006345468107610941, -0.006835184060037136, 0.0026778082828968763, 0.04109445959329605, 0.021568339318037033, 0.006293370388448238, 0.01201366912573576, 0.031466852873563766, -0.0006313558551482856, -0.005600474774837494, -0.013534914702177048, 0.01908850111067295, -0.006105819717049599, 0.014180922880768776, -0.019692832604050636, -0.005689040292054415, -0.025277677923440933, 0.002761164214462042, -0.018494591116905212, -0.01618146523833275, -0.0020526391454041004, -0.01622314192354679, 0.015827201306819916, 0.017473481595516205, -0.00036305401590652764, -

### Write embedded data to Qdrant

In [24]:
qdrant_client.upsert(
    collection_name="Amazon-items-collection-00",
    wait=True,
    points=pointstructs,
)

UpdateResult(operation_id=0, status=<UpdateStatus.COMPLETED: 'completed'>)

### Define a function for data retrieval

In [25]:
def retrieve_data(query, k=5):
    query_embedding = get_embedding(query)
    results = qdrant_client.query_points(
        collection_name="Amazon-items-collection-00",
        query=query_embedding,
        limit=k,
    )
    return results

### Test retrieval

In [35]:
retrieve_data("What kind of earphones can I get?", k=10).points

[ScoredPoint(id=20, version=0, score=0.5232439, payload={'description': 'Open Ear Headphones, Bluetooth 5.3 Earbuds with 60H Playtime IPX7 Waterproof Wireless Earbuds Immersive Premium Sound True Wireless Open Ear Earbuds with Earhooks for Running, Walking and Workouts 【Open-ear Design Headphones】Feature with a new generation of true open-ear wireless earbuds design, the headphones can rest gently and firmly fit your ears without entering your ear canal, which will reduce stress and hearing loss after extended wear. There is no pinching of the auricle, no blockage of the ear canal, and no pain or damage to hearing. 【Powerful Stereo Sound】Equipped with 16.2 millimeters vibrating diaphragm speaker driver, bluetooth headphones providing pure balanced audio and clarity output for all music genres with soft audio and immerse yourself in the wonderful world of music. 【Hear Your Surroundings】Open earbuds that rest on your ears without covering them, you can hear your music and your surroundings at the same time. Whether you are cycling, walking, running, working out or driving, you can always be aware of your surroundings, knowing you are safe and alert for changes in your environment. 【Comfort and Secure Fit】 The open earbuds can avoid wearing discomfort caused by in-ear or over-ear headphones. Flexible, secure-fitting silicone ear hooks and an ergonomic design ensure the bluetooth earphones stay comfortable and secure during hiking, running and other outdoor activities. 【Charge on the go & IPX7 Waterproof】Earbuds last 11 hours of playback time with one charge and can be extended up to 60 hours with a portable charging case in use. Plus, wireless headphones boast IPX7-rated protection that prevents ordinary splashing water and rain. (Please note: The charging case is not waterproof)', 'image': 'https://m.media-amazon.com/images/I/4117ZOD57DL._AC_.jpg', 'rating_number': 779, 'price': 39.99, 'average_rating': 4.4, 'parent_asin': 'B0CBMPG524'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=44, version=0, score=0.5121211, payload={'description': 'Wireless Earbuds, Bluetooth 5.3 Headphones with Microphone, 37H Playback LED Power Display, In-Ear Headphones Deep Bass, IPX7 Waterproof, Ultra-Light Earphones with Charging Case, Smart Touch, Sport S23-vine earbuds', 'image': 'https://m.media-amazon.com/images/I/41kzh9WqgwL._AC_.jpg', 'rating_number': 184, 'price': 14.99, 'average_rating': 4.2, 'parent_asin': 'B0B9FTVL58'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=39, version=0, score=0.49235946, payload={'description': "TUNEAKE Kids Headphones, Over Ear Kids Headset Stereo, Volume Limited 94dB, Foldable Adjustable Headphones for Kids, 3.5mm Jack Kid Headphones for Boys Girls Toddler School Laptop Travel Tablet, Pink 🍀LISTENING VOLUME🍀: Designed with 94dB volume-limiting technology, kids headphones offer adequate hearing protection that your child cannot listen to music or watch videos at dangerously high levels. Kids headphones for school NOTE: NO microphone, but you can still speak into the device's mic that you are plugged into and will hear you. 🍀KID-SIZED FOR COMFORT🍀: The padded headband and soft ear cups on the kids headphones boys provides a comfy fit for kids. The adjustable headband makes it well-suited to your child. With cushy, perforated mesh on the cushioned cups, your child's head will not feel hot. 🍀FOR EASY STORAGE AND PORTABILITY🍀: Children's headphones feature a folding design that can fold up to help reduce their size, easy to store in your child's backpack. The earmuffs can be rotated by 90°for easy hanging on the neck. 🍀WIDE COMPATIBILITY🍀: A 3.5mm aux port including a 120cm cable gives you the option to connect directly to devices. Compatible with all Smartphones, Chromebooks, iPads, Tablets, Computers, Laptops, and all 3.5mm audio jack devices. 🍀FUN FOR KIDS🍀: Kids headphones wired has easy controls that can allow children to use them without any difficulty. Whether your little one needs school headphones for online learning, or just to jam out to their own tunes, finding the kid headphones for them is worthwhile. Lifetime Support, Easy to Reach Customer Service.", 'image': 'https://m.media-amazon.com/images/I/3155NTPBIzL._AC_.jpg', 'rating_number': 264, 'price': 9.99, 'average_rating': 4.5, 'parent_asin': 'B0C142QS8X'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=12, version=0, score=0.48160842, payload={'description': "TELSOR Wireless Earbuds for iPhone, Bluetooth Headphones Touch Control Stereo Sound Bluetooth Earbuds with Noise Cancelling Mic for Calls, 30H Playtime, IPX7 Waterproof Earbuds for Android, Black ♬【Bluetooth】Pair instantly with an uninterrupted and stable transmission with Bluetooth 5.1. AVRCP, HCP, HSP, and A2DP profiles are supported. The wireless earbuds are compatible with most Bluetooth enabled iPhones, Andriods, smart TVs, computers, etc. Each wireless earbuds will pair with each other when they are removed from the charging case. From here, enable Bluetooth on your chosen device and pair with the headphones. ♬【Clear Call & Sound quality】Each wireless earbuds features a 10mm diameter speaker and 2 microphones to reduce ambient noise and transmit your voice for a clear call in any environment. For the music enjoyers, these wireless earbuds offer a deep bass for an immersive musical experience. ♬【Long Battery Life & Quick Charge】Get up to 6 hours of playtime on a single charge or up to 30 hours when using the charging case. A full charge takes 2 hours in the charging case. The charging case itself is charged using USB-C. ♬【IPX7 Waterproof & Ergonomic Design】TELSOR wireless earbuds feature IPX7 Waterproof nano-coating to effortlessly protect the wireless earbuds from rain and sweat alike. The lightweight, ergonomic design fits in the ear without adding any discomfort or stress, making them perfect for offices, runs, and workouts. ♬【Smart Touch Control】There won't be a need to reach for your phone when using these wireless earbuds. Tapping the wireless earbuds enables you access to volume control, pause/play/skip, answer/hang up, and voice assistant. ♬【Ideal Gift】TELSOR Wireless Earbuds are great for friends and family as Birthday gifts, Valentine's Day gift etc.", 'image': 'https://m.media-amazon.com/images/I/41vGX4B4DFL._AC_.jpg', 'rating_number': 141, 'price': 9.99, 'average_rating': 4.3, 'parent_asin': 'B0C6K1GQCF'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=33, version=0, score=0.46068424, payload={'description': 'Siniffo Upgraded Bone Conduction Headphones Wireless Bluetooth 5.3 Open Ear Sports Earphones with Mic, Sweat Resistant Headset for Workout, Running, Gym, Hiking, Driving, Cycling, Commuting 【Premium Sound Quality】Experience premium audio delivered through your cheekbone with our bone conduction technology. Engineered with both audio enhancement technology and exclusive OT closed anti-leakage technology, X15 bone conduction headphones brings the immersive listening experience from deep, rich bass to accurate mids and crisp, clean highs, you’ll hear every note with a new sense of clarity. 【Extreme Comfort & Secure Fit】X15 workout headphones adopt a open-ear design with an ergonomic scientific arc, combined with a high-performance vibrator and an ultra-lightweight design. It is comfortable and painless to wear for a long time while ensuring a secure fit. In addition, X15 headphones feature IP56 waterproof rating for outdoor and indoor sports, such as running, hiking and even intense workout, etc. Recommended for small head sizes and for those who prefer a more snug fit. 【Bluetooth 5.3 & HD Call】X15 Bluetooth open-ear headphones deliver a more stable and faster wireless connection to your devices and up to 30% lower gaming latency. X15 also features noise-canceling microphone for clear and stable voice communication. Independent button controls allow you to easily adjust volume, play music, answer or end\xa0calls, activate Siri, or switch between music and game mode. 【8-Hour Battery Life & Quick Charge】Strong battery supports 8 hours of continuous music and calls. Siniffo X15 running headphones adopt Type-C quick charge and feature a 10-minute quick charge for up to 1.5 hours of listening. Enjoy your favorite music all day long! 【What You Get】1*Bone Conduction Headphones, 1*Type-C Quick Charging Cable, 4*Sponge Earplugs, 1* Manual, 30-day Return and 2-year Warranty. We care about all details, each gym headphones is tested manually. For those looking for high-quality sport headphones at a reasonable cost, we believe Siniffo X15 headset is a good choice. If you have any questions, please do not hesitate to contact us.', 'image': 'https://m.media-amazon.com/images/I/316qHea1cyL._AC_.jpg', 'rating_number': 196, 'price': None, 'average_rating': 4.0, 'parent_asin': 'B0BNHVLF7G'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=6, version=0, score=0.432051, payload={'description': '8 Pairs Powerbeats Pro Ear Tips Buds, 4 Size Replacement Soft Flexible Fit in Case Noise Reduce Silicone Rubber Earbuds Eartips Wing Skin Accessories Compatible with Beats Flex/BeatsX - White 【 Compatibility 】 These ear tips compatible with Powerbeats Pro, compatible with Powerbeats High Performance, compatible with Beats Flex, compatible with Beats X, compatible with Beats Fit Pro, compatible with Beats Studio Buds. 【 Material 】 Made of soft flexible premium silicone, provide more noise isolation, in-ear stability and a lasting comfort. And They are Water-washable, durable, flexible, removable and replaceable. 【 Nice Sound Quality 】 These ear tips can offer a good seal to reduce some of the outside noise and allow you to focus on your audio, provide a better sound listening experience. 【 More Size Options, Better Fit 】 Small Medium Large and Double Flange 4 different sizes, complies comfortably with your individual ear shape. Fit in the charging case, no need to remove the foam when you put earphone into the charging case. 【 Package include 】 8 pairs replacement ear tips, tips only, earphone not include.', 'image': 'https://m.media-amazon.com/images/I/31Q1I3K1KuL._AC_.jpg', 'rating_number': 269, 'price': 7.99, 'average_rating': 4.5, 'parent_asin': 'B0B14HTZ59'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=21, version=0, score=0.42842007, payload={'description': "RUSAM GA33 A Enhanced Edition TWS Game Earbuds True Wireless Stereo Headset Low Latency Bluetooth 5.2 Headphones Wireless Deep Bass Touch Control Earbuds HD Physical Noise Cancellation Earphones,White 【Advanced Bluetooth 5.2 Technology】RUSAM GA33 A built-in Bluetooth 5.2 chip,stable connection within 10 meters, Even if you cover your ears with your hands, you won't be disconnected,smooth like a wired headset. 【Game/Music Mode】The game/music mode can be switched by key operation to meet the needs of different usage scenarios.In music mode,13mm Dual Coil Dynamic Drivers，strong bass effect,heavy and low frequency all around the ear, shock more penetrating. 【Low Latency Game Mode】45ms low latency,there is a sound effect adjustment function in the game mode,and the subtle sound can also be captured to clearly distinguish the enemy's position. 【Long battery life】Built-in 40MAH battery in the headset, 400MAH battery in the charging box, can listen to music continuously for 3-4 hours, and the charging box can be charged 4-5 times,and the play time or music time can be up to 14 hours with the charging compartment. 【Cool appearance】Cool design,supplemented by various RGB lights,beautiful colors.In the Enhanced Edition,the earphones and charging box have increased surface treatment, more delicate touch, and more enhanced details.", 'image': 'https://m.media-amazon.com/images/I/41nvyEcip0L._AC_.jpg', 'rating_number': 128, 'price': None, 'average_rating': 3.5, 'parent_asin': 'B09WCFC5D9'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=48, version=0, score=0.4128428, payload={'description': 'QearFun Cat Earbuds for Kids, Kawakii Wired Earbud & in-Ear Headphones Gift for School Girls and Boys with Microphone and Lovely Earphones Storage Case(Blue) ', 'image': 'https://m.media-amazon.com/images/I/41F9aQvWyHL._AC_.jpg', 'rating_number': 245, 'price': 9.98, 'average_rating': 3.7, 'parent_asin': 'B0B67ZFRPC'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=49, version=0, score=0.39918977, payload={'description': 'Cleaner Kit for AirPods Pro, 4 in 1 Earbuds Cleaning Pen, Bluetooth Headphone Cleaning Pen for Airpods, Airpods Pro 1 2 3 and Other Earphones, Keyboard, Mouse, Cellphones, Laptop, Camera (White) 【4-IN-1 DESIGN】The airpod cleaning kit is divided into 4 parts - flocking sponge, high-density brush, long-bristle brush and metal tip, which can deeply clean the earbuds and earphone charging compartment at different angles, making your earphones like new 【MULTIFUNCTIONAL CLEANING KIT】The metal tip can precisely remove the dirt in the sound hole of the earbuds, and the high-density brush under the cleaning pen tip is used to clean the fine dust. There are also flocking sponge ends and long-bristle brush ends, the earphone charging compartment can also be well cleaned, and the long-bristle end is suitable for cleaning computer peripherals such as keyboards (When replacing the flocking sponge and long-bristle brush, please rotate and pull out out) 【SAFE AND HEALTHY】 The brush end is made of environmentally friendly and soft materials, which will not damage the earbuds. Frequent cleaning of the earphones and keeping the earbuds clean can effectively improve the wearing experience and make the earphones more comfortable to wear for a long time 【PORTABLE】Segmented pen cover design, multiple functions in one, the airpods pro cleaner kit is small in size and light in weight, only the size of a pen, it can be easily put into a pocket, easy to store and carry out 【UNIVERSAL】This cleaning pen can not only clean the earphones, but also the earphone charging case, mobile phone, keyboard, mouse, microphone, camera, laptop, etc. Compatible with cleaning most bluetooth earphones, TWS on the market (If you have any questions, you can contact us by Amazon mail, to provide you with better after-sales service)', 'image': 'https://m.media-amazon.com/images/I/31WdFX5UrmL._AC_.jpg', 'rating_number': 158, 'price': None, 'average_rating': 4.3, 'parent_asin': 'B0B7495RL6'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=23, version=0, score=0.38329095, payload={'description': 'LENRUE Bluetooth Speakers, Waterproof Portable Speakers with TWS, 24 Playtime, Stereo Sound, Wireless for Home Shower Pool Beach Outdoor ✅ ♫Loud and Crisp Sound - Upgrade 2 high quality horns, plays very clear and it can get very loud. Wthout any distortion and noise. ✅ ♫IPX6 Waterproof - Portable bluetooth speakers updates IPX6 waterproof and dustproof, portable for shower, pool, beach. The speaker cannot be completely immersed in water. ✅ ♫Portable & Hanging - Equipped with a detachable lanyard, the portable speaker can be hung on bicycles, motorcycles, backpacks, and tents. The speaker is an ideal gift. ✅ ♫Wireless Stereo Pairing - Bluetooth speakers perform powerful surround sound by connecting 2 speakers together. ✅ ♫ Multi Play Way - Wireless speakers adopt seamless Bluetooth 5.0. Support TF and AUX. Portable for phones, tablets, laptops.', 'image': 'https://m.media-amazon.com/images/I/51JNM+vdb4L._AC_.jpg', 'rating_number': 1495, 'price': 13.59, 'average_rating': 4.5, 'parent_asin': 'B0BS15TRJ3'}, vector=None, shard_key=None, order_value=None)]